### ISSUE TITLE
Compatible release clause behaviour differs from PEP440 for versions with prerelease

### ISSUE THREAD

**Issue by timdiels** [pypa/packaging#100]
[PEP440](https://www.python.org/dev/peps/pep-0440/#compatible-release) gives the example that `~= 1.4.5a4` should be equivalent to `>= 1.4.5a4, == 1.4.*`, however:

```
>>> from packaging.specifiers import SpecifierSet
>>> '1.4.6' in SpecifierSet('~=1.4.5a4', prereleases=True)  # incorrect
False
>>> '1.4.6' in SpecifierSet('>=1.4.5a4, ==1.4.*', prereleases=True)  # correct
True
```

[It appears there has been a misinterpretation](https://github.com/pypa/packaging/blob/master/packaging/specifiers.py#L395), treating `~=1.4.5a4` as `>= 1.4.5a4, == 1.4.5.*`. Compare this to PEP440: "If a pre-release, post-release or developmental release is named in a compatible release clause as V.N.suffix , then the suffix is ignored when determining the required prefix match".

My environment:

```
(venv) $ pip freeze
appdirs==1.4.2
attrs==16.3.0
chicken-turtle-util==4.0.1
lxml==3.7.3
numpy==1.12.0
packaging==16.8
patool==1.12
pkginfo==1.4.1
py==1.4.32
pypandoc==1.3.3
pyparsing==2.2.0
pytest==3.0.6
pytest-capturelog==0.7
requests==2.13.0
six==1.10.0
(venv) $ python --version
Python 3.5.2
```

**Comment by di** [comment]
It seems like that wording in the PEP 440 is indeed at odds with the actual implementation, which explicitly treats prereleases differently: https://github.com/pypa/packaging/blob/fc86d7eeeeb68a224974c30e98d420560c75b0a4/packaging/specifiers.py#L452-L462

Currently prereleases are _not_ ignored, but treated as it's own segment, so you get this instead:

```
~=1.4.5a4 as
>=1.4.5a4, ==1.4.5.*
```

Given that @dstufft [was the one to originally implement it like this](https://github.com/pypa/packaging/commit/55c58bcf764ab747bd2d5b120bfca1e6bf7839c2#diff-adc16878ac93246a7b458f23ef645ae4b84d9e342e498b029bb17c0f0fbdab3eR387-R398), perhaps he has an idea about why?

**Comment by jiasli** [comment]
This bug becomes more outstanding as `pip`'s new resolver is more strict and fails due to incompatible dependencies.
