### ISSUE TITLE
Ability to quickly sort or check sorting of version numbers as a CLI tool

### ISSUE THREAD

**Issue by durin42** [pypa/packaging#111]
From irc today:

```
17:07 < dstufft> like python -m packaging.version sort 4.5 6.7 3.4 -> 3.4 4.5 6.7
[...]
17:10 < dstufft> probably something like python -m packaging.version sort --verify 3.4 4.5 6.7 might be reasonable
```

**Comment by venthur** [comment]
Enforcing 100% code coverage might be a bit too strict here.

This patch [introduces](https://github.com/pypa/packaging/pull/183/files#diff-832b3493370c7de79eff39a50afebf2aR464) a code block that cannot (easily) be tested with pytest:

```python
if __name__ == "__main__":
    sys.exit(main())
```

As you'll see, I already put all the code into the `main` function so i can test them properly, but this little block above remains uncovered. If you insist on 100% coverage, please tell me how to execute this using pytest+coverage across all supported Python versions.

Cheers!

**Comment by brettcannon** [comment]
So what's the hope for this? To simplify doing:
```python
sorted(map(packaging.version.Version, ["4.5", "6.7", "3.4"]))
```

As you can tell from the one-liner, I'm not sure if this is necessary for us to implement and thus maintain. 😉

**Comment by uranusjr** [comment]
I think the implication is to have a CLI interface. Although this is likely more suited for a small wrapper script (on PyPI or elsewhere) than in packaging directly.

**Comment by pradyunsg** [comment]
This belongs in a wrapper script, outside of packaging IMO. There's multiple potential operations that someone could want to do with the `Version` class or with version strings in general -- providing a rich (or restricted) CLI does not bring much value.

If someone can make the case for why such a script should live in this library, please feel welcome to reopen this (or file a new issue, if you can't) but I'm gonna close this for now to reflect that it's unlikely to happen unless someone can come up with a reason that hasn't been brought up in the last 5+ years. :)
