### ISSUE TITLE
Missing Git tag for 17.1 release

### ISSUE THREAD

**Issue by felixonmars** [pypa/packaging#127]
It would be nice to keep PyPI releases and git tags in sync :)

**Comment by jaraco** [comment]
My preferred way to handle this synchronization issue is to have the tags drive releases using setuptools-scm. If this project wishes to adopt such a workflow, I’d be happy to contribute a PR.

**Comment by pradyunsg** [comment]
@dstufft Could you push the tags for the releases?

**Comment by jaraco** [comment]
Actually, now that I think about it, the issue isn't necessarily synchronization, but a manual release process. If the release process went through CI like Travis, then only tagged commits would get released. I highly recommend adopting that.

**Comment by felixonmars** [comment]
Update: 18.0 was released and the tag is missing too.

**Comment by pradyunsg** [comment]
Pushed tags for both 17.1 and 18.0.

19.0 will have its tag pushed as well.
