### ISSUE TITLE
Set up CI for macOS and Windows

### ISSUE THREAD

**Issue by brettcannon** [pypa/packaging#154]
Assuming my PEP 425 work lands, there will be a need to have CI for macOS, Windows, and Linux for which there is no CI for the first two. The options I know of are:

1. Move to Azure Pipeilnes which has all platforms
2. Add macOS on Travis and add their experimental Windows support
3. Add macOS on Travis and add AppVeyor

**Comment by shreyasbapat** [comment]
Can I take this up?

**Comment by jaraco** [comment]
@shreyasbapat  I can't say authoritatively as I'm not a maintainer of this package, but I'd definitely support you making some progress on this effort and help guide a pull request through to acceptance.

**Comment by shreyasbapat** [comment]
Sure thing! Thanks @jaraco :)
You will see a Pull Request Soon!

**Comment by brettcannon** [comment]
Some notes:
- [Travis file](https://github.com/pypa/packaging/blob/master/.travis.yml)
- [tox.ini](https://github.com/pypa/packaging/blob/master/tox.ini)
- [setup-python action](https://github.com/actions/setup-python)
- [Workflow syntax](https://help.github.com/en/articles/workflow-syntax-for-github-actions)
- [Context and expression syntax](https://help.github.com/en/articles/contexts-and-expression-syntax-for-github-actions)
