### ISSUE TITLE
Master branch is failing with pytest >= 5.0

### ISSUE THREAD

**Issue by pganssle** [pypa/packaging#166]
I restarted the last build for the master branch and Python versions >= 3.5 are [failing to match some part of exception messages](https://travis-ci.org/pypa/packaging/jobs/541530561#L644). Given that `python_version >= 3.5` describes the support matrix for `pytest >= 5.0` and these same builds were passing a month ago, I suspect that the problem is that the current version of `packaging`'s tests have not been updated to be compatible with the latest `pytest`.

Lately I've been recommending pinning all test dependencies - though I have no actually effective and reasonable way of doing this myself yet (working incrementally on some mechanism to update the dependencies that doesn't spam me with a million individual PRs like dependabot does). That would help the user experience for contributors here, though in the short term just pinning `pytest` will probably work for a while.

**Comment by pradyunsg** [comment]
Let's just add a constraint to pytest <= 5 to our test dependencies here. That's a "quick fix".

I'll try to make some time later to fix this stuff properly.

**Comment by asottile** [comment]
#174 has a fix for this
