### ISSUE TITLE
[19.1] Tests fail on most architectures

### ISSUE THREAD

**Issue by mbakke** [pypa/packaging#177]
Hello,

Running the test suite of 19.1 fails on architectures other than x86_64. Build logs below.

i686: https://ci.guix.gnu.org/log/7mi4gk6w21l4j4lzjgcz9ary5bawcnvx-python-packaging-19.1

aarch64: https://ci.guix.gnu.org/log/6v67bysg3k6sxg1n0cxl9yjl8s1bs3c6-python-packaging-19.1

armhf: https://ci.guix.gnu.org/log/c25i80m1vydhscg27ggcqnz4sm9wr61i-python-packaging-19.1

Any idea what is wrong?

**Comment by di** [comment]
Can you see if #176 resolves it for you?

**Comment by pradyunsg** [comment]
Gonna close this now that #176 has merged. Please let us know if this issue still persists for you. :)
