### ISSUE TITLE
19.1 circular dependencies

### ISSUE THREAD

**Issue by scarabeusiv** [pypa/packaging#178]
With the 19.1 release the package now depends on attrs, which in turn depends directly on setuptools. Packaging on its own is a direct dependency of setuptools as well. This means when you are bootstraping the packages it can't be done properly.

Looking at attrs they rely on find_packages and few other tiny features of setuptools 40+ so I don't think it is possible to build them just with distutils...
  https://github.com/python-attrs/attrs/blob/master/setup.py

Could maybe tags became optional feature? That would be good enough for us to not hard-require it...

**Comment by pradyunsg** [comment]
We can probably drop attrs and change the class in question to a handwritten implementation with __slots__, if nothing else.

**Comment by 183amir** [comment]
Is there going to be a release with this fix soon?

**Comment by pradyunsg** [comment]
There's some discussion on #179.
