### ISSUE TITLE
Removal of 'm' flag from tag in Python 3.8

### ISSUE THREAD

**Issue by rdb** [pypa/packaging#180]
Python 3.8 removes the existence of the `m` ABI flag:
https://bugs.python.org/issue36707
https://docs.python.org/dev/whatsnew/3.8.html#build-and-c-api-changes

Changes are needed in `packaging.tags` for platforms that do not define `SOABI` in the configuration.  Linux and macOS wheels already are built without the `m` suffix.  On Windows, pip fails to install binary wheels with the following error:
```
ERROR: mypackage-1.0.0-cp38-cp38-win_amd64.whl is not a supported wheel on this platform.
```

Fixing this is required to support installing binary Windows wheels in Python 3.8.

**Comment by rdb** [comment]
For the record, the ABI tag mechanism in `packaging.tags` does not suffer from this issue, as it reports the correct ABI tag, `cp38`.  It is the `pep425tags` modules in wheel and pip that need fixing:

pypa/pip#6874
pypa/wheel#303

**Comment by brettcannon** [comment]
@rdb since packaging.tags is doing the right thing I'm going to close this issue, but thanks for noticing this and reporting it upstream as appropriate!
