### ISSUE TITLE
Add type annotations to packaging.tags

### ISSUE THREAD

**Issue by cjerdonek** [pypa/packaging#189]
pip's `pep425tags` module [has type annotations](https://github.com/pypa/pip/blob/d2b7082932a59585ea6198cbf375758fae949c67/src/pip/_internal/pep425tags.py), so it would be good for `packaging.tags` to have type annotations as well before [switching pip away](https://github.com/pypa/pip/issues/6908) from `pep425tags`.

It looks like this would require adding a mypy CI check.

**Comment by pradyunsg** [comment]
@brettcannon I'm in for shipping with type annotations inline.

**Comment by di** [comment]
I'm working on this.
