### ISSUE TITLE
Set the URL for the project in GitHub as https://packaging.pypa.io/

### ISSUE THREAD

**Issue by brettcannon** [pypa/packaging#192]
Basically make it easier to find the link to the docs. 😄 Requires an administrator.

**Comment by pradyunsg** [comment]
@dstufft @di @ewdurbin Could one of you give @pypa/packaging-committers the Admin bit, on this repository?

**Comment by pradyunsg** [comment]
Thanks Ernest! Seems like someone did this before I could get to it. 🙃
