### ISSUE TITLE
Improve detection of debug builds on Windows

### ISSUE THREAD

**Issue by chrahunt** [pypa/packaging#194]
From pypa/pip#3535:

> From pypa/pip#3383 it'd be nice to have better detection of debug builds on Windows.
> 
> @zooba said on [#3383 (comment)](https://github.com/pypa/pip/issues/3383#issuecomment-173267692)
> 
> > `Py_DEBUG` is never going to be in `pyconfig.h` on Windows as the header is static (no autoconf) and debug/no-debug is determined using the preprocessor at build.
> > `sys.gettotalrefcount` is protected by `Py_REF_DEBUG`, which is not guaranteed to always be set when `Py_DEBUG` is set. That said, `distutils.command.build` tests for it, so it's probably safe enough (or at least, there'll be twice as many bugs when it breaks...).
> > The most reliable check is probably going to be:
> > ```python
> > any(x[0] == '_d.pyd' for x in imp.get_suffixes())
> > ```
> > 
> > 
> > The only issue with this is that the `imp` module is deprecated - Python 3.3 and later should really use:
> > ```python
> > '_d.pyd' in importlib.machinery.EXTENSION_SUFFIXES
> > ```

**Comment by brettcannon** [comment]
Actually the best way on Windows would be via `importlib.machinery.WindowsRegistryFinder.DEBUG_BUILD`:

https://github.com/python/cpython/blob/master/Lib/importlib/_bootstrap_external.py#L1677

I've opened https://bugs.python.org/issue38102 to make it officially documented.
