### ISSUE TITLE
Configure black to match flake8's line length (or vice-versa)

### ISSUE THREAD

**Issue by brettcannon** [pypa/packaging#203]
flake8 uses 78, black uses 88. That leads to conflicts when developing. We should choose one and then configure the other to respect the chosen line length.

**Comment by pradyunsg** [comment]
I'm fine with either.

**Comment by di** [comment]
flake8 is already configured to use 88:

https://github.com/pypa/packaging/blob/7890ca820eca8580d63fcadae727e95a70daec27/.flake8#L2

@brettcannon do you have some local config that might be overriding this?

**Comment by brettcannon** [comment]
Nope, I will have a look to see if I can figure out why flake8 is always complaining at me.
