### ISSUE TITLE
Extras not parsed as extras when importlib.metadata.requires is used

### ISSUE THREAD

**Issue by fridex** [pypa/packaging#211]
I'm trying to automatically parse package extras with [importlib.metadata.requires](https://docs.python.org/3.9/library/importlib.metadata.html#distribution-requirements). The official documentation states the following code snippet as an example:

```python
>>> requires('wheel')  
[
  "pytest (>=3.0.0) ; extra == 'test'",
  "pytest-cov ; extra == 'test'"
]
```

I would assume the string to be compatible with `packaging.requirement.Requirement` implementation which would provide me a parsed representation of the requirement (actually, this is also stated in the [`requires` docstring](https://github.com/python/cpython/blob/5faff977adbe089e1f91a5916ccb2160a22dd292/Lib/importlib/metadata.py#L500-L507)).

However, the implementation of `Requirement` keeps the extra in marker instead of parsing it as `extras`:

```python
>>> from packaging.requirements import Requirement
>>> Requirement("pytest (>=3.0.0) ; extra == 'test'").__dict__
{'name': 'pytest', 'url': None, 'extras': set(), 'specifier': <SpecifierSet('>=3.0.0')>, 'marker': <Marker('extra == "test"')>}
>>> Requirement("pytest (>=3.0.0) ; extra == 'test'").marker._markers[0]
(<Variable('extra')>, <Op('==')>, <Value('test')>)
```

If I try to evaluate marker, it causes an exception (which is expected to my understanding of [PEP-0508](https://www.python.org/dev/peps/pep-0508/#environment-markers)):

```python
>>> Requirement("pytest (>=3.0.0) ; extra == 'test'").marker.evaluate()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fpokorny/.local/share/virtualenvs/solver-WFdZ3ODT/lib/python3.6/site-packages/packaging/markers.py", line 296, in evaluate
    return _evaluate_markers(self._markers, current_environment)
  File "/home/fpokorny/.local/share/virtualenvs/solver-WFdZ3ODT/lib/python3.6/site-packages/packaging/markers.py", line 221, in _evaluate_markers
    lhs_value = _get_env(environment, lhs.value)
  File "/home/fpokorny/.local/share/virtualenvs/solver-WFdZ3ODT/lib/python3.6/site-packages/packaging/markers.py", line 203, in _get_env
    "{0!r} does not exist in evaluation environment.".format(name)
packaging.markers.UndefinedEnvironmentName: 'extra' does not exist in evaluation environment.
```

Using the bracket syntax of extras works as expected:

```python
>>> from packaging.requirements import Requirement
>>> Requirement("pytest[test] (>=3.0.0)").__dict__
{'name': 'pytest', 'url': None, 'extras': {'test'}, 'specifier': <SpecifierSet('>=3.0.0')>, 'marker': None}
```

According to [PEP-0508](https://www.python.org/dev/peps/pep-0508/#environment-markers), "extra" can be treated as a marker, which should not be used during interpretation (which explains the above exception to me).

I would like to know if the parsing behavior of strings as returned by `importlib.metadata.requires`  is expected. Also, is there any other way how to parse a package require extras? The solution that comes to my mind is to iterate over `_markers` explicitly with checks for `Variable`'s `value` equal to `extra` as shown below:

```python
>>> [m[2].value for m in Requirement("pytest (>=3.0.0) ; extra == 'test'").marker._markers if m[0].value == 'extra']
['test']
```

Please note I'm using a private variable of `Marker` instance, which is not good. A suitable public API would be more appropriate.

Thanks for any help in advance!

**Comment by pradyunsg** [comment]
There's a difference between the two cases.

- `pytest[test] >= 3.0.0` means we depend on `pytest >= 3.0.0` and the optional dependencies of pytest's `test` extra.
- `pytest (>=3.0.0) ; extra == 'test'` means we depend on `pytest >= 3.0.0` if we're installing `mypkg[test]` but not otherwise -- i.e. pytest is the optional dependency here.

**Comment by pradyunsg** [comment]
> ```python
> >>> requires('wheel')  
> [
>   "pytest (>=3.0.0) ; extra == 'test'",
>   "pytest-cov ; extra == 'test'"
> ]
> ```

To that end, this means wheel has no required dependencies, and optionally depends on `pytest` and `pytest-cov` if someone does `pip install wheel[test]`.

**Comment by pradyunsg** [comment]
(noting for folks following via email -- I made a lot of edits to my first post in this thread)

**Comment by fridex** [comment]
@pradyunsg that explains the current behavior. Thanks!
