### ISSUE TITLE
What should dev-requirements.txt be used for?

### ISSUE THREAD

**Issue by brettcannon** [pypa/packaging#214]
A few times I have found that the dependencies listed in `dev-requirements.txt` do not match what gets installed by tox. So what should `dev-requirements.txt` be used for? Is it just what is required to run the tests using pytest directly? What about the linters (which I care about since that's necessary to work with VS Code)? Basically should `dev-requirements.txt` be kept in sync with tox or should it have targeted usage that is documented in the file?

**Comment by pradyunsg** [comment]
Anything's fine with me. I'm not using that file in my workflows.

I'm actually inclined to suggest that we remove it if you're not using it in your workflow either -- since reduced duplication and consistent environment setup from tox should make life easier.

**Comment by brettcannon** [comment]
@pradyunsg so I am, but it's to more easily support my VS Code configuration to make sure `tox`, `black`, `flake8`, and `pytest` all get installed (otherwise VS Code is going to ask me to do the installations individually as I use those features). After that it would be stuff necessary to do a release.

I'll think about whether it's worth it to me to keep for editor-related installs or just skip it and install those manually.

**Comment by pradyunsg** [comment]
One of these days, maybe I'll come around to asking you about your setup/workflows for Python on VS Code and improve mine. :P

**Comment by brettcannon** [comment]
I decided to just delete it for now. If/when I commit a VS Code `settings.json` then I may come back to recreating the file.
