### ISSUE TITLE
Add PyPy to GitHub Actions

### ISSUE THREAD

**Issue by brettcannon** [pypa/packaging#235]
Looks like PyPy and PyPy3 have been added to the [runners](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners). Probably just need to look at how the tests are run under tox for PyPy and then duplicate it as another job under `Test`.

**Comment by Sangarshanan** [comment]
Hey @brettcannon, was looking to make my first contribution...could I use take this up ?

**Comment by brettcannon** [comment]
@Sangarshanan go for it! Something to probably look out for is to see how `tox.ini` runs under PyPy differently than CPython.

Also feel free to tweak the current test job to say "CPython" to help differentiate.
