### ISSUE TITLE
Dynamically detect abi3 support

### ISSUE THREAD

**Issue by brettcannon** [pypa/packaging#238]
Check supported file extensions for importing for one that contains `.abi3.`.

Came up as part of #187 .

**Comment by chrahunt** [comment]
We dropped this from pip in pypa/pip#7367 so it is not a blocker for `packaging.tags` integration.

More generally, I think that it's important to consider that someone may be relying on an implementation detail, but it's not something that we ever guaranteed. If we do want to go this route officially then better via a new/updated PEP describing how other implementations can advertise ABI compatibility.

IMO we can close this issue and wait for it to come up, if it comes up.
