### ISSUE TITLE
Release version 20.0

### ISSUE THREAD

**Issue by di** [pypa/packaging#252]
I think we're ready for a 20.0 release. [Here's what this would include](https://github.com/pypa/packaging/blob/master/CHANGELOG.rst#200---master), is anything missing?

Any volunteers to make the release?

**Comment by brettcannon** [comment]
I did the last one so calling "not it" 😁 (plus I'm just too busy with other stuff that I let wither while I got the `packaging.tags` API stuff straightened out). But I will say that https://github.com/pypa/packaging/blob/master/docs/development/release-process.rst is up-to-date based on what I did for the release, although automating it when a release is produced here on GitHub via an action and a PyPI token scoped to the project would probably be a worthwhile effort.

**Comment by pradyunsg** [comment]
I'm happy to make the release. :)

**Comment by pradyunsg** [comment]
@brettcannon I just filed #253 for discussion on automation of the release process. I've listed a few options, so I'd like to hear if you have any suggestions/inputs on what approach to take. :)

**Comment by pradyunsg** [comment]
Heads up: I'll come around to this today/tomorrow.

**Comment by pradyunsg** [comment]
The release has been made. :)
