### ISSUE TITLE
packaging.tags.compatible_tags is not re-creating a new iterator

### ISSUE THREAD

**Issue by jeroendecroos** [pypa/packaging#257]
With the release of pip==20.0.1 a problem was observed as described here: https://github.com/pypa/pip/issues/7626

The problem was tracked back to packaging.tags.compatible_tags

When no iterator is given for parameter platforms, an iterator is initialized:
https://github.com/pypa/packaging/blob/e664cdd5c82b706ba4c5368477c8d7081fd99456/packaging/tags.py#L332

Which is then used in:
https://github.com/pypa/packaging/blob/e664cdd5c82b706ba4c5368477c8d7081fd99456/packaging/tags.py#L334

This should be the otherway around, to not reuse the exhausted iterator.

**Comment by brettcannon** [comment]
I'm not quite seeing the bug on our side. If no iterator is provided then we create one from `_platform_tags()` and then we use it in the `for` loop. The API specifically asks for an iterator, so I'm not seeing the issue. Are you suggesting we test for `platforms is None`?

**Comment by brettcannon** [comment]
nm, I see the issue now; it's the `for` loop using `platforms` being within another `for` loop.
