### ISSUE TITLE
missing changelog entry for 20.1

### ISSUE THREAD

**Issue by ewdurbin** [pypa/packaging#260]
While reviewing a [dependabot upgrade for warehouse](https://github.com/pypa/warehouse/pull/7299), I noticed that it reported:

<img width="486" alt="Screen Shot 2020-01-24 at 5 31 03 PM" src="https://user-images.githubusercontent.com/1200832/73108838-69a82100-3ecf-11ea-9fb5-e8b1ce502f0d.png">

There appears to be some helpful information on the GitHub release though, which should probably be reflected in the changelog: https://github.com/pypa/packaging/blob/master/CHANGELOG.rst

**Comment by di** [comment]
I'm also not seeing any commits bumping the version for this release, version is still `20.1.dev0` here: https://github.com/pypa/packaging/blob/master/packaging/__about__.py#L21.

The Github release https://github.com/pypa/packaging/releases/tag/20.1 is also tagged at https://github.com/pypa/packaging/commit/d49fdc500a7c057b71851847ff8d7cc92865bcf2 which seems incorrect.

**Comment by pradyunsg** [comment]
Uhh... Lemme check.

**Comment by pradyunsg** [comment]
Fixed now -- turns out, I `git push`ed to my fork, instead of here and the tag creation is a manual step -- where I didn't verify that master was indeed updated (because I thought I pushed to the right place). This has been a good week. :)

The longer-term fix is to automate myself out of the release process -- which is what I'm doing in #253. :)

**Comment by di** [comment]
@pradyunsg In the future, can we make PRs for releases instead of just pushing to master?

**Comment by pradyunsg** [comment]
Yeah, sounds reasonable to me. :)

**Comment by pradyunsg** [comment]
FYI -- the release process is here: https://github.com/pypa/packaging/blob/master/docs/development/release-process.rst
