### ISSUE TITLE
Manylinux support logic ignores overrides

### ISSUE THREAD

**Issue by aragilar** [pypa/packaging#263]
With the switch to use packaging.tags in pip 20, the values in _manylinux.py may be overridden by https://github.com/pypa/packaging/blob/d49fdc500a7c057b71851847ff8d7cc92865bcf2/packaging/tags.py#L660, which assumes that if a newer manylinux is supported, older ones must be too, and overrides the value (pip lacked this additional logic, hence why there were no previous issues). While this logic could be removed, a better solution would seem to be to have an explicit override (as contained in #262). This would seem to me to solve https://github.com/pypa/pip/issues/3689.

There's an associated pip issue (https://github.com/pypa/pip/issues/7648), which I created to track when this issue is fixed in pip.

**Comment by chrahunt** [comment]
As mentioned in #262, implementing `manylinux_compatible` as described in [PEP 600](https://www.python.org/dev/peps/pep-0600/#package-installers) should do what we want.

**Comment by brettcannon** [comment]
#280 implemented PEP 600, so I believe this issue is taken care of. If I'm misunderstanding what is being asked then please let me know and we can reopen the issue.
