### ISSUE TITLE
Try running tests in GitHub Actions using nox

### ISSUE THREAD

**Issue by brettcannon** [pypa/packaging#268]
I _think_ if the ["test" GitHub Action](https://github.com/pypa/packaging/blob/master/.github/workflows/test.yml) was updated to run nox via `python -m nox --session test-${{ matrix.python_version }}` we could then simplify that entire thing to use nox. We could then also merge the two jobs in that file as the noxfile already does the right thing for PyPy vs. CPython.

**Comment by brettcannon** [comment]
This is all based on https://nox.thea.codes/en/stable/tutorial.html#testing-against-different-and-multiple-pythons. This would be a key differentiator compared to tox as that tool uses no dots in the version number of Python to be used.

**Comment by pradyunsg** [comment]
Useful reference for how to do that: https://github.com/github-actions-playground/friends-pradyunsg/blob/master/.github/workflows/test.yml

**Comment by brettcannon** [comment]
Yeah, I have started to leave `name` off when it isn't obvious from the command being run or it's really long.

**Comment by brettcannon** [comment]
So I tried to make this work and our support for Python 2.7 is the problem. 😭  After stripping all the f-strings from the `noxfile.py` it shows how nox itself doesn't support Python 2.7 itself, so I don't think we can make this clean transition until we drop Python 2.7 (or go back to tox which I doubt you want to do after all the work you did the build the release session).

**Comment by pradyunsg** [comment]
:eyes:

But... that's exactly what the aforementioned reference shows! Lemme file a PR for adopting those changes in our CI setup. :)
