### ISSUE TITLE
Release version 20.2?

### ISSUE THREAD

**Issue by xuhdev** [pypa/packaging#272]
Could you make a bugfix release? The bug of https://github.com/pypa/packaging/pull/234 has been negatively impacting a lot of (at least our) projects that run on Raspberry Pi and rely on Travis for CI. Thank you in advance.

cc @bdwyer2

**Comment by pradyunsg** [comment]
I can do that.

/cc @pypa/packaging-committers I'll be making a packaging 20.2 release sometime tomorrow afternoon (IST). Please holler if master is not in a releasable state, or if you have any other concerns with a release. :)

**Comment by xuhdev** [comment]
Thank you so much @pradyunsg !

**Comment by xuhdev** [comment]
@pradyunsg Any progress? :)

**Comment by pradyunsg** [comment]
Hah! I actually did start working on this, but our newly introduced automated releases weren't "ready for primetime".

I'll cut the release after merging #274. :)

**Comment by pradyunsg** [comment]
Done!

**Comment by xuhdev** [comment]
Awesome!  Thanks!

**Comment by pradyunsg** [comment]
Looks like my changes on the changelog weren't being staged as part of #274, so I'm gonna release a 20.3 with unreviewed changes.

**Comment by brettcannon** [comment]
You can release a 20.2.post1 instead since there is no code changes.

**Comment by pradyunsg** [comment]
Too late. 🙈

*hides under pillow*

**Comment by xuhdev** [comment]
@pradyunsg  Would you mind also updating https://github.com/pypa/pip/tree/master/src/pip/_vendor/packaging ? I can do it, just in case there is nothing magic that one has to do with an update...
