### ISSUE TITLE
Unexpected handling of versions with "local" components by pip

### ISSUE THREAD

**Issue by ashb** [pypa/packaging#275]
**Environment**

* pip version: pip 20.0.2 from /home/ash/.virtualenvs/clean/lib/python3.7/site-packages/pip (python 3.7)
* Python version: 3.7
* OS: linux

**Description**

I am investigating using version epochs for a local/private "fork" of a project, and want to push out updates without accidental upgrading to the upstream version.

So I have specified my requirement as `apache-airflow>=1!1.10.7+local.6`, and since there is an epoch in there (`1!` prefix) I should expect that to fail. As per [PEP-440 Summary of permitted suffixes and relative ordering](https://www.python.org/dev/peps/pep-0440/#summary-of-permitted-suffixes-and-relative-ordering)

> The epoch segment of version identifiers MUST be sorted according to the numeric value of the given epoch. If no epoch segment is present, the implicit numeric value is 0.

However it appears that the implicit epoch is being treated as 1.

```
Collecting apache-airflow>=1!1.10.7+local.6
  Created temporary directory: /tmp/pip-unpack-jitssjpx
  Starting new HTTPS connection (1): files.pythonhosted.org:443
  https://files.pythonhosted.org:443 "GET /packages/d4/8e/109906b658256027467e34a9f2e0c82a133ff8b39b8f08c73ee03334b641/apache_airflow-1.10.9-py2.py3-none-any.whl HTTP/1.1" 200 4639908
  Downloading apache_airflow-1.10.9-py2.py3-none-any.whl (4.6 MB)

```

If I change the explicit epoch I required to `2!` then it works as expected:

```
No matching distribution found for apache-airflow>=2!
```

(Yes I acknowledge I am abusing version epochs for this purpose, but this behaviour is still against what the spec says)

**Comment by pradyunsg** [comment]
Taking a customary skim through this, ISTM that this is indeed a case of hitting a whole bunch of edge cases. :)

It'll probably take a bit more time to understand the nuances than I have right now. For now, I've transferred this to pypa/packaging.

**Comment by ashb** [comment]
I think the quick summary is:

Pip follows the PEP-440 spec as defined around local versions, but I (naievly) assumed it would follow what ever packaging.version did with it's ordering/comparison of Version objects (and I checked they were "valid", not LegacyVersion after parsing)

**Comment by pradyunsg** [comment]
If pip's (and therefore packaging's) behaviour is consistent with pep 440, I don't think there's anything actionable here.

**Comment by ashb** [comment]
I'd like the PEP to be changed/relaxed if possible! It makes local versions much much harder to use, and makes them behave _very_ differently to debian etc.

I'd like the spec to treat local versions how ever `packaging.version` is treating them.

**Comment by pradyunsg** [comment]
@ashb I see -- in that case, consider clearly articulating *why* (and possibly *how*) the behavior should change at https://discuss.python.org/c/packaging, to make a case for changing the behavior.

Updates to such standards need a discussion for concensus-building (which may, or may not, be trivial) that there's a problem and then, how we want to solve it. :)

**Comment by pradyunsg** [comment]
Closing since #321 is the approach we've taken here.
