### ISSUE TITLE
Document major, minor, and micro properties on Version

### ISSUE THREAD

**Issue by brettcannon** [pypa/packaging#276]
https://github.com/pypa/packaging/blob/318a0347665fb0990ed33f00e0434615ece5ea3a/packaging/version.py#L404-L417

**Comment by deveshks** [comment]
Hi @brettcannon 

I can probably take up this PR, since this is listed as [good first issue](https://github.com/pypa/packaging/contribute)

Could you please let me know what are we looking to do here?

**Comment by brettcannon** [comment]
@deveshks document the `major`, `minor`, and `micro` properties on the `Version` class. IOW make sure the [documentation for `Version`](https://packaging.pypa.io/en/latest/version/#packaging.version.Version) is up-to-date.

**Comment by deveshks** [comment]
Hi @brettcannon ,

I assume that means updating the three properties in [here](https://github.com/pypa/packaging/blob/master/docs/version.rst#reference) ?

**Comment by brettcannon** [comment]
@deveshks yep

**Comment by deveshks** [comment]
Hi @brettcannon 

Have created a PR for the same
