### ISSUE TITLE
Dev versions not contained in final release specifiers

### ISSUE THREAD

**Issue by YakDriver** [pypa/packaging#277]
This behavior seems strange to me. Am I doing this wrong?

```python
from packaging.specifiers import SpecifierSet
from packaging.version import Version

SpecifierSet('>=0.0').contains(Version('1.0'))     # True - expected
SpecifierSet('>=0.dev0').contains(Version('1.0'))   # True - expected
SpecifierSet('>=0.0').contains(Version('1.0.dev0'))  # False - what?
SpecifierSet('>=0.0').contains(Version('99.9.9.dev0'))   # False - what??
```

Tested on:
Python 3.7.6
packaging 20.1

**Comment by di** [comment]
If the `SpecifierSet` does not contain dev/pre releases, then any version with a dev/pre version will not be considered part of that set:

```python
>>> SpecifierSet('>=0').contains(Version('1.0.dev0'))
False
>>> SpecifierSet('>=0.dev0').contains(Version('1.0.dev0'))
True
```

Here's the implementation:

https://github.com/pypa/packaging/blob/a59f31831164dfa085895409bba0942ad0f4df76/packaging/specifiers.py#L783-L790

**Comment by YakDriver** [comment]
This misses a common real-world scenario. The workaround (i.e., adding "dev" to the specifier) is easy but seems messy.

The scenario it misses is this. Say, for example, that you have a release 1.0 of a project. It has a configuration file that is marked as compatible with `>=1.0` of the project.  Release 2.0 of the project comes out and nothing in the configuration file spec has changed so it is still marked at `>=1.0`. But, now we have Release 2.1.dev0 and suddenly packaging says that the config file is not usable since `>=1.0` does not include `2.1.dev0`.

That's a problem. Also, the workaround of marking the config file as `>=1.0.dev0` is confusing.

**Comment by di** [comment]
Sorry, I'm not totally sure I follow your use case. What do you mean by "a config file that is marked as compatible with `>=1.0` of the project"? How are you marking a config file as compatible?

The primary use case for `SpecifierSet` is requirements files and specifying sub-dependencies for packages. In those use cases, users rarely want a pre-release or dev-release if they have not explicitly specified it.

**Comment by YakDriver** [comment]
Oh, yes. Sorry for not explaining. We're piggybacking on your logic to determine the compatibility of config files with projects, similar to requirements files and sub-dependencies. The config files contain a specifier and then the project itself determines if it is compatible by comparing its version with the config file specifier. In that use case, a dev version isn't automatically incompatible with a final release.

**Comment by di** [comment]
I'm not sure that's a very common real-world scenario, at least this is the first I've heard of it. 

If you need to do this and have control over the implementation, just enable prereleases for the `SpecifierSet` yourself:

```python
>>> s = SpecifierSet('>=0')
>>> s.prereleases = True
>>> s.contains(Version('1.0.dev0'))
True
```

**Comment by YakDriver** [comment]
Awesome! Thanks for the help. I'll do so. This is the simple project piggybacking on your logic: https://github.com/YakDriver/compatibleversion

**Comment by di** [comment]
Great, and given that we don't need to make any changes to `packaging` here, I'm going to close this issue as well.
