### ISSUE TITLE
./tests/hello-world-invalid-class: Heuristics.Broken.Executable FOUND

### ISSUE THREAD

**Issue by slmi** [pypa/packaging#279]
Hello,

clamscan -ir packaging.git/
packaging.git/tests/hello-world-invalid-class: Heuristics.Broken.Executable FOUND

----------- SCAN SUMMARY -----------
Known viruses: 6779666
Engine version: 0.102.2
Scanned directories: 25
Scanned files: 94
Infected files: 1
Data scanned: 1.63 MB
Data read: 0.84 MB (ratio 1.95:1)
Time: 13.676 sec (0 m 13 s)

Impacted version: >=20

**Comment by di** [comment]
Yup, that's intentional.
