### ISSUE TITLE
Support PEP 600

### ISSUE THREAD

**Issue by mattip** [pypa/packaging#280]
I am interested in getting [PEP 600](https://www.python.org/dev/peps/pep-0600/) and general `manylinux_X_Y` support out, since it turns out `manylinux2014` limits us to `glibc2.17`, and NumPy has found that many trigonometric functions are inaccurate in that glibc. Also, the aarch64 gcc compiler in manylinux2014 has a bug that was fixed upstream but  it seems will take quite some time to percolate out into the image. xref numpy/numpy#15763, numpy/numpy#7518, pypa/manylinux#494.

I am not sure how to do this and still respect the [Package Installers](https://www.python.org/dev/peps/pep-0600/#package-installers) section of the PEP. Any thoughts, especially in light of PR gh-262?

**Comment by brettcannon** [comment]
In general the changes are probably going to be:

1. Create a generator that yields all glibc versions from the current version on down to 2.5 where `manylinux1` started
2. Have that generator also emit the old `manylinux` tags at the right place to match what PEP 600 says they are now aliases for
3. Also respect the new `_manylinux` module semantics when generating tags
4. Update the rest of the code to use the new function

**Comment by brainwane** [comment]
I think there needs to be a tracking issue for full rollout and I [asked about that in Discourse just now](https://discuss.python.org/t/pep-600-future-manylinux-platform-tags-for-portable-linux-built-distributions/2414/28).

**Comment by mattip** [comment]
Does the tracking issu belong in pypa/manylinux ?

**Comment by mattip** [comment]
Closing, thanks

**Comment by brainwane** [comment]
Thanks @mattip - https://github.com/pypa/manylinux/issues/542 will be a good place for tracking this progress. And thank you for your work!
