### ISSUE TITLE
Specifier equivalence check does not consider version equivalence

### ISSUE THREAD

**Issue by uranusjr** [pypa/packaging#282]
Orginally reported as pypa/pip#7900.

Currently the specifier equivalence check compares the contained version as a string. `packaging.version.parse` should be used instead to ensure equivalent version strings are considered equal.

Minimal reproduction:

```pycon
>>> from packaging.specifiers import SpecifierSet
>>> SpecifierSet("==2.8.0") == SpecifierSet("==2.8.0")
True
>>> SpecifierSet("==2.8.0") == SpecifierSet("==2.8")
False
```

**Comment by di** [comment]
The issue is that the specifiers are not considered equal:
https://github.com/pypa/packaging/blob/d3f305de93230c44c2923f46b5a18f9a83607509/packaging/specifiers.py#L139-L149

```python
>>> from packaging.specifiers import Specifier
>>> Specifier('==2.8.0') == Specifier('==2.8')
False
>>> Specifier('==2.8.0') == Specifier('==2.8.0')
True
>>> Specifier('==2.8.0')._spec
('==', '2.8.0')
>>> Specifier('==2.8')._spec
('==', '2.8')
```

We should canonicalize the version when comparing them, I created https://github.com/pypa/packaging/pull/283 to fix this.
