### ISSUE TITLE
BSD Licesne Clarification

### ISSUE THREAD

**Issue by CleanHit** [pypa/packaging#287]
Which of the BSD Licenses described in this [SPDX](https://github.com/spdx/license-list-data/tree/master/json/details) repository is actually being used?

**Comment by di** [comment]
It's the 2-Clause BSD License: https://github.com/pypa/packaging/blob/master/LICENSE.BSD

**Comment by CleanHit** [comment]
@di Thank you, I've asked because I'm using this specification to scan for OSS licenses in my code. The code scans the registered license name in Python repositories e.g. PyPi. Unfortunately, it says "Apache Software License, BSD License (BSD or Apache License, Version 2.0)" instead of "BSD 2 Clause and Apache 2.0" , "BSD 2-Clause and Apache-2.0" or "BSD-2-Clause and Apache-2.0". 

This is actually very important because there are many software compliance tools that scan for used OSS libraries in code for legal reasons, as those must be listed in the code that uses them. It would be great, if you could change the the license name in PyPy to one of the options that I've mentioned above (not all permutations are listed :) ). So it will comply with the [SPDX](https://github.com/spdx) effort to standardise the usage of open source software licenses.

**Comment by di** [comment]
I think we can do that: #289.
