### ISSUE TITLE
version wrongly compares '1.2' and '1.2_5'

### ISSUE THREAD

**Issue by LubosKolouch** [pypa/packaging#299]
```python
def compare_versions(ver_1, ver_2):
    """ Compare versions and return the result"""

    v_1 = version.parse(ver_1)
    v_2 = version.parse(ver_2)

    if v_1 > v_2:
        return 1

    if v_1 < v_2:
        return -1

    return 0


assert compare_versions('0.1', '1.1') == -1
assert compare_versions('2.0', '1.2') == 1
assert compare_versions('1.2', '1.2_5') == -1
assert compare_versions('1.2.1', '1.2_1') == 1
assert compare_versions('1.2.1', '1.2.1') == 0
```
```
Traceback (most recent call last):
  File "ch-1.py", line 25, in <module>
    assert compare_versions('1.2', '1.2_5') == -1
AssertionError
```

Obviously, 1.2 should be greater than development 1.2_5 alpha version?

**Comment by brettcannon** [comment]
So there's two things going on here. One is that `1.2_5` is not considered a pre-release or an in-dev release according to [PEP 440](https://www.python.org/dev/peps/pep-0440/):
```python
>>> ver2 = packaging.version.parse("1.2_5")
>>> ver2.is_devrelease
False
>>> ver2.is_prerelease
False
>>> ver2.is_postrelease
False
```
I think what you probably want is `1.2_a5` if this is meant to be an alpha-5 release and you want to keep that underscore (`1.2a5` is the normalized form).

Two, `1.2_5` is a `LegacyVersion` instance while `1.2` is a `Version` instance. We _just_ updated the docs this week with a note about how `LegacyVersion` instances always compare less than `Version` instances.

So everything is actually working as intended.
