### ISSUE TITLE
Dropping Python 2 support

### ISSUE THREAD

**Issue by pradyunsg** [pypa/packaging#305]
My proposal: Drop it in 21.0. :)

Holler if you're not on board.

**Comment by ShadowJonathan** [comment]
Py2 is EOL, it would only make sense.

What minimal py3 version will be supported from now on then? I saw this being referenced from a PR in the context of typing, with typing annotations being added only in 3.5 (iirc)

**Comment by brettcannon** [comment]
@ShadowJonathan it will depend on what pip chooses to support at the time we drop this.

**Comment by pradyunsg** [comment]
I'd imagine we'll drop Python 3.5 as well (since it'll be EoL by Jan 2021).

**Comment by pradyunsg** [comment]
Since no one is opposed to this, I say it's decided that we'll drop support for Python 2 from packaging in early 2021.

**Comment by pradyunsg** [comment]
I'd say we should also deprecate 3.4 and 3.5 at the same time, since they're also EOL.

**Comment by brettcannon** [comment]
So when are we going to do this? It's 2021 and @jdufresne was nice enough to beat all of us to a PR. Any reason to wait? Is one last Python 2 release necessary for Apple Silicon support?

**Comment by brettcannon** [comment]
Release 20.9 is out. Any reason to put this off any longer?

**Comment by pradyunsg** [comment]
Nope.

**Comment by brettcannon** [comment]
Done! 🥳🎉🎊🍾 (there aren't enough emojis for this 😁).
