### ISSUE TITLE
A specifier of "==*" is not handled properly

### ISSUE THREAD

**Issue by pfmoore** [pypa/packaging#307]
This is somewhat useless, and I'm not *entirely* sure it's PEP 400 conformant, but the following fails:

```
>>> from packaging.specifiers import SpecifierSet
>>> from packaging.version import Version
>>> s = SpecifierSet("==*")
>>> s.contains(Version("1.0.0"))
False
```

This form of specifier is used in pip's test suite [here](https://github.com/pypa/pip/blob/20.1.1/tests/functional/test_install.py#L1498). I'll fix the test by using a different specifier, but I think that `packaging` should either reject the specifier as invalid, or treat it as "always matching".

**Comment by di** [comment]
A specifier of `==*` is not a valid `Specifier`:

```
>>> from packaging.specifiers import Specifier
>>> Specifier("==*")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dustiningram/git/pypa/packaging/packaging/specifiers.py", line 112, in __init__
    raise InvalidSpecifier("Invalid specifier: '{0}'".format(spec))
packaging.specifiers.InvalidSpecifier: Invalid specifier: '==*'
```

Instead when used in a `SpecifierSet` it becomes a `LegacySpecifier`:

```
>>> from packaging.specifiers import SpecifierSet
>>> s = SpecifierSet("==*")
>>> s._specs
frozenset({<LegacySpecifier('==*')>})
```

Which means that a `Version` will never be contained in it, but a `LegacyVersion` will, but only if the version is an exact string match:

```
>>> from packaging.version import LegacyVersion
>>> s = SpecifierSet("==*")
>>> s.contains(LegacyVersion("*"))
True
```

PEP 440 says:

> The specified version identifier must be in the standard format described in [Version scheme](https://www.python.org/dev/peps/pep-0440/#version-scheme), but a trailing `.*` is permitted on public version identifiers as described below.

where the minimum valid version is a single-digit release segment, so I would expect that particular test to use `==7.*` (or `==7.1.*`) instead.

**Comment by pfmoore** [comment]
Bah. Legacy stuff. I didn't even realise there was a `LegacySpecifier` class (I *did* know about `LegacyVersion`).

Thanks for the clarification. I had indeed changed that test as described.

I wonder whether pip's code is being inconsistent in where it allows "legacy" versions of stuff like this. Certainly we have at least one code path that was accepting a version string of "7" as matching a specifier string of "==*". Never mind, my immediate issue is addressed, and there's no bug in packaging.

**Comment by pradyunsg** [comment]
> I wonder whether pip's code is being inconsistent in where it allows "legacy" versions of stuff like this.

It's not -- we just allow it everywhere. :)

**Comment by pfmoore** [comment]
Nope, the triggering case would have worked then. I think the new resolver code uses `Version` (i.e., non-legacy) in some places. But this is both off-topic here, and not really that important anyway 🙂
