### ISSUE TITLE
Latest version

### ISSUE THREAD

**Issue by 0xFF1E071F** [pypa/packaging#309]
Hello
What is the latest version right now?
You tagged 20.1 on github but pypi.org show 20.4 as latest?

Thank you =)

**Comment by brettcannon** [comment]
It's [20.4 and it's tagged](https://github.com/pypa/packaging/releases/tag/20.4). I don't know why GitHub isn't showing that as the latest version under https://github.com/pypa/packaging/releases/ and I don't see an obvious way in the web UI to tell it to change what it considers the latest.

**Comment by brettcannon** [comment]
Ah, I see what happened. @pradyunsg _tagged_ the releases but didn't _draft_ a release on GitHub itself.

@pradyunsg was that on purpose or an oversight?

**Comment by pradyunsg** [comment]
An oversight!

**Comment by pradyunsg** [comment]
We should probably auto-push tags in the release automation. :)

**Comment by 0xFF1E071F** [comment]
Thanks for reply
