### ISSUE TITLE
packaging.tags does not support `*-none-any` wheels for non`-py*` interpreter tags

### ISSUE THREAD

**Issue by pganssle** [pypa/packaging#311]
**Environment**

* pip version: 20.1.1 (19.3.1 is the last working version)
* Python version: pypy3.6.9-7.3.1
* OS: Arch Linux

**Description**
It appears that `pip` does not consider `pp3-none-any` a valid wheel tag on PyPy 3 after `pip==19.3.1`. This is a problem for [the PEP 615 backport](https://github.com/pganssle/zoneinfo), since it has both a C and a pure Python implementation, and I want to ship a wheel containing only the pure Python implementation *only for PyPy* (anyone else who doesn't have a wheel should fall back to the sdist).

Here is a minimal reproducing bash script, which downloads an arbitrary universal wheel and renames it to end with `pp3-none-any.whl`:

```bash
cd $(mktemp -d)
pypy3 -m venv venv
source venv/bin/activate
pip install -U pip

pip --version
# pip 20.1.1 from /tmp/tmp.IV5fhdUrQt/venv/site-packages/pip (python 3.6)

python --version
# Python 3.6.9 (2ad108f17bdb, Apr 07 2020, 02:59:05)
# [PyPy 7.3.1 with GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]

pip wheel -w wheelhouse tzdata==2020.1
mv wheelhouse/tzdata-2020.1-py2.py3-none-any.whl\
   wheelhouse/tzdata-2020.1-pp3-none-any.whl
pip install -t target --no-index -f wheelhouse tzdata
# Looking in links: wheelhouse
# ERROR: Could not find a version that satisfies the requirement tzdata (from versions: none)
# ERROR: No matching distribution found for tzdata
```

**Expected behavior**
The expected behavior is to install the `pp3` wheel when on PyPy, which was the behavior in 19.3.1:

```
$ pip --version
pip 19.3.1 from /tmp/tmp.IV5fhdUrQt/venv/site-packages/pip (python 3.6)
$ pip install -t target --no-index -f wheelhouse tzdata
Looking in links: wheelhouse
Processing ./wheelhouse/tzdata-2020.1-pp3-none-any.whl
Installing collected packages: tzdata
Successfully installed tzdata-2020.1
```

It's possible that this is another manifestation of pypa/pip#7629.

**Comment by pradyunsg** [comment]
Moved as requested, and, well, /cc @mattip @brettcannon for thoughts. :)

**Comment by brettcannon** [comment]
Three things. One, @pganssle why don't you want CPython users to use the pure Python wheel and have to build from source otherwise? If the pure Python wheel is good enough for PyPy why isn't it good enough for e..g Alpine users? And if they really care about performance couldn't they choose to skip the wheel to build from source?

Two, using `cp3` as an example, where do you put it in the tag list (and remember you need to insert it twice; `none-<os>` and `none-any` as I'm assuming zero ABI support)? And do note that the ordering is a bit funky when it comes to interpreter version so you will have to be very specific about where in the list below you suggest it goes.

And three, if you add `cp3` and `pp3`, what about `cp39-none-<OS>` and `cp39-none-any`? Where do they go?

1. cp38-cp38-win_amd64
1. cp38-abi3-win_amd64
1. cp38-none-win_amd64
1. cp37-abi3-win_amd64
1. cp36-abi3-win_amd64
1. cp35-abi3-win_amd64
1. cp34-abi3-win_amd64
1. cp33-abi3-win_amd64
1. cp32-abi3-win_amd64
1. py38-none-win_amd64
1. py3-none-win_amd64
1. py37-none-win_amd64
1. py36-none-win_amd64
1. py35-none-win_amd64
1. py34-none-win_amd64
1. py33-none-win_amd64
1. py32-none-win_amd64
1. py31-none-win_amd64
1. py30-none-win_amd64
1. py38-none-any
1. py3-none-any
1. py37-none-any
1. py36-none-any
1. py35-none-any
1. py34-none-any
1. py33-none-any
1. py32-none-any
1. py31-none-any
1. py30-none-any

I still don't think the ABI-agnostic interpreter versions are worth it, but people keep bringing them up _just_ often enough I'm going to start arguing against them if we can agree as to where they should land in the order and someone submits a PR for whatever we agree to.

**Comment by pganssle** [comment]
> Three things. One, @pganssle why don't you want CPython users to use the pure Python wheel and have to build from source otherwise? If the pure Python wheel is good enough for PyPy why isn't it good enough for e..g Alpine users? And if they really care about performance couldn't they choose to skip the wheel to build from source?

This is because the pure python version isn't just "good enough" for PyPy, it's *better*, but *only* on PyPy, because PyPy needs to use the cpyext compatibility layer in order to make use of any C extensions, which is dramatically slower than JIT-compiled PyPy code. See the benchmarks in [the PyPy support PR](https://github.com/pganssle/zoneinfo/pull/74); generally the pure Python version is ~10x faster:

```

**Comment by pganssle** [comment]
> Three things. One, @pganssle why don't you want CPython users to use the pure Python wheel and have to build from source otherwise? If the pure Python wheel is good enough for PyPy why isn't it good enough for e..g Alpine users? And if they really care about performance couldn't they choose to skip the wheel to build from source?

This is because the pure python version isn't just "good enough" for PyPy, it's *better*, but *only* on PyPy, because PyPy needs to use the cpyext compatibility layer in order to make use of any C extensions, which is dramatically slower than JIT-compiled PyPy code. See the benchmarks in [the PyPy support PR](https://github.com/pganssle/zoneinfo/pull/74); generally the pure Python version is ~10x faster (here's one example):

```
Running utcoffset in zone America/New_York
c_zoneinfo: mean: 3.45 µs ± 52.71 ns; min: 3.40 µs (k=5, N=100000)
py_zoneinfo: mean: 336.64 ns ± 11.60 ns; min: 325.69 ns (k=5, N=1000000)
pytz: mean: 213.31 ns ± 5.82 ns; min: 204.82 ns (k=5, N=10000000)
```

Those numbers are reversed on other platforms, and I would prefer other platforms to build from source. If I want to add the ability to opportunistically fall back to the pure python library on musl, etc, I'll put that in the `setup.py`.

> Two, using `cp3` as an example, where do you put it in the tag list (and remember you need to insert it twice; `none-<os>` and `none-any` as I'm assuming zero ABI support)? And do note that the ordering is a bit funky when it comes to interpreter version so you will have to be very specific about where in the list below you suggest it goes.
>
> And three, if you add `cp3` and `pp3`, what about `cp39-none-<OS>` and `cp39-none-any`? Where do they go?

I am not sufficiently familiar with the issues of ordering (and in my case it doesn't matter, since I won't be shipping any `py3` wheels — it would only matter if I needed to ship both a `pp3` and a `pp38` wheel or something of that nature, in which case it's just important that `pp38` come before `pp3`). Could we not use the [example ordering laid out in PEP 425](https://www.python.org/dev/peps/pep-0425/#id1), which does include these abi-agnostic interpreter-specific versions?

> 1. cp33-cp33m-linux_x86_64
> 2. cp33-abi3-linux_x86_64
> 3. cp3-abi3-linux_x86_64
> 4. cp33-none-linux_x86_64*
> 5. cp3-none-linux_x86_64*
> 6. py33-none-linux_x86_64*
> 7. py3-none-linux_x86_64*
> 8. cp33-none-any
> 9. cp3-none-any
> 10. py33-none-any
> 11. py3-none-any
> 12. py32-none-any
> 13. py31-none-any
> 14. py30-none-any

By that ordering, I think (though I could be wrong) it would go:

1. cp38-cp38-<os>
2. cp38-abi3-<os>
3. cp3-abi3-<os>
4. cp38-none-<os>
5. cp3-none-<os>
6. cp38-none-any
7. cp3-none-any
8. cp37-abi3-<os>
9. …

**Comment by brettcannon** [comment]
One other wrinkle in this (and one of the reasons I dropped support for this tag that I just remembered), is there is no consistent way to get the `3` in `pp3`. The generic code that calculate the interpreter tag is:

https://github.com/pypa/packaging/blob/59e14881910bf836c43b7d319ea08ab321ccfb39/packaging/tags.py#L776-L787

You will notice it reads from the `py_version_nodot` config variable; there isn't an explicit major/minor split here. And with 3.10 coming we know that minor versions can be more than a digit so you can't just slice of the last digit.

So to make this work you will either have to special-case PyPy for interpreter version support (which we just stopped doing at PyPy's request), or someone will have to introduce some other way to consistently get the interpreter version as discrete components (possibly config variables for the major and minor versions separately which may help with #308

**Comment by brettcannon** [comment]
Due to this continuing to come up, if someone wanted to added a `cp38-none-any` tag back in, I won't object (I just won't do the work either 😄 ). Pragmatically, the issue of having an odd tag triple totally outweighs the number of times I have explained why I left it out. 😉
