### ISSUE TITLE
Typo in documentation for "Specifiers"

### ISSUE THREAD

**Issue by domdfcoding** [pypa/packaging#322]
Hi,

The documentation for "Specifiers" starts as follows:

> A core requirement of dealing with dependency is the ability to specify what versions of a dependency are acceptable for you.

To be grammatically correct it should say:

> A core requirement of dealing with **dependencies** is the ability to specify what versions of a dependency are acceptable for you.

The docs for "Markers" has the correct wording.

Happy to submit a PR if you'd like

**Comment by pradyunsg** [comment]
Nice catch!

Please do file a PR. :)
