### ISSUE TITLE
Equality operator not implemented on Requirement

### ISSUE THREAD

**Issue by lkollar** [pypa/packaging#325]
Reproducer:

```python
>>> packaging.requirements.Requirement("a") == packaging.requirements.Requirement("a")
False
```

Is this expected behaviour?

**Comment by brettcannon** [comment]
There's no comparison operator implemented on the class, so this may be on purpose. What's your specific use-case for wanting this? I ask because without a concrete version specifier of what's installed this is a very ephemeral thing.

And as a work-around, you could compare the string representations of the objects.

**Comment by lkollar** [comment]
I was trying to do this in a test and was wondering why it doesn't have it implemented. I ended up working it around with the string comparison, just like you suggested. 

I opened the issue mainly to clarify if this is an omission or if there is a good reason for not having it implemented. I don't have a strong opinion here. My only data point is that 'pkg_resources.Requirement' implements it, but I'm not even sure it's a goal at all to attempt any sort of compatibility with it.

**Comment by brettcannon** [comment]
I don't know the history of the module to know if compatibility is in any way a goal.

**Comment by sbidoul** [comment]
I also stumbled on this requirement in a testing context. It would be nice to have.

**Comment by 8day** [comment]
Comparison will require normalization of `"dist; (((extra == 'doc')) and python_version == '3.8.6')"` and `"dist; 'doc' in extra and '3.8.6' in python_version"` to `"dist; python_version == '3.8.6' and extra == 'doc'"`, which requires a lot of work.

Also, considering that variable `extra` from environment markers is likely to be redefined in the near future, as discussed at https://discuss.python.org/t/the-extra-environment-marker-and-its-operators/, support for equality operator most likely will be added after such discussion will result in some PEP.

**Comment by pelson** [comment]
I was about to roll my sleeves up and implement this, when I saw that it has already been implemented in https://github.com/pypa/packaging/pull/499.

As a result of this:

```
>>> from packaging.requirements import Requirement

>>> Requirement('a==1') == Requirement('a== 1')"
True
```

And specifically, the motivating reproducer in the issues description is also working:

```
>>> import packaging.requirements 
>>> packaging.requirements.Requirement("a") == packaging.requirements.Requirement("a")
True
```

Therefore, suggest this can be closed.
