### ISSUE TITLE
New release including type hint fixes?

### ISSUE THREAD

**Issue by aneeshusa** [pypa/packaging#338]
I'm using packaging in a few projects and it's been very nice - I still remember learning that packaging existed, ripping out a ton of custom parsing code & replacing it with some packaging imports, and feeling very satisified.
I tried including packaging in my mypy setup recently and noticed some type errors that https://github.com/pypa/packaging/pull/310 looks to have fixed.
Could you cut a new release of packaging including that change? I didn't see any particular release cadence documented in https://packaging.pypa.io/en/latest/development/release-process/.

**Comment by brettcannon** [comment]
We aim to definitely release annually, but otherwise we just release as needed. It's probably coming up to time to do another release, although I don't know if the other maintainers have plans to make any changes soon that would warrant postponing a release.

**Comment by pradyunsg** [comment]
None from me. If anything, I'd hold off until after pip 20.3, so that I don't have to do another round of vendoring updates there. :)

**Comment by henryiii** [comment]
Hasn't this happened and can't this be closed?

**Comment by di** [comment]
Yep!

**Comment by aneeshusa** [comment]
Thank you! I have pulled in the new release and confirmed it fixes the issues.
