### ISSUE TITLE
Provide access to the structured information about a version.

### ISSUE THREAD

**Issue by tomprince** [pypa/packaging#34]
We have built some automation around releases and testing that involve inspecting the version, to determine what type of release something is, and where to publish it (etc.).

Currently we are using a regex to parse pre PEP-440 versions. I was planning on using `packaging` to replace this, but it appears that packaging doesn't expose this information in a structured way.

**Comment by tomprince** [comment]
It would also be nice to be able to construct versions from structured data.

**Comment by dstufft** [comment]
Can you be more specific about what you're looking for exactly? Is this specifically for pre-PEP440 versions?

**Comment by tomprince** [comment]
> Is this specifically for pre-PEP440 versions?

No. We are currently parsing our pre-PEP440 version using [this regex](https://github.com/ClusterHQ/flocker/blob/7e9b0a5050b7694f93528652d9c2ac3c8d8cbd13/flocker/common/version.py#L10-L25). We are planning on switching to PEP440 compatible versioning, and rather than update that regex to support the new versioning scheme, I'd like to use packaging to parse it.

It looks like the `_Version` named-tuple has all the information I want, but the interface perhaps isn't ideal.

**Comment by dstufft** [comment]
Ok, so you want access to things like the release segment, the epoch, etc?

**Comment by tomprince** [comment]
Yes. The following is a spike of what I was thinking.
```python
def _parse_version(version):
    """
    Parse a version of Flocker.

    :return FlockerVersion: The parsed version.

    :raises UnparseableVersion: If the version can't be parsed as a Flocker
        version.
    """
    packaging_version = Version(version)._version
    major, minor, micro = packaging_version.release
    if packaging_version.pre:
        pre_l, pre_n = packaging_version.pre
        if pre_l == 'rc':
            pre_release = pre_n
            weekly_release = None
        elif pre_l == 'a':
            pre_release = None
            weekly_release = pre_n
    else:
        pre_release = None
        weekly_release = None
    if packaging_version.post:
        documentation_revision = packaging_version.post[1]
    else:
        documentation_revision = None
    if packaging_version.dev:
        commit_count = packaging_version.dev[1]
        assert packaging_version.local[0].startwith('gn')
        commit_hash = packaging_version.local[0][2:]
    else:
        commit_count = None
        commit_hash = None
    if packaging_version.local and len(packaging_version.local) > 1:
        dirty = packaging_version.local[1]
    else:
        dirty = None
    return FlockerVersion(
        major=major,
        minor=minor,
        micro=micro,
        pre_release=pre_release,
        weekly_release=weekly_release,
        documentation_revision=documentation_revision,
        commit_count=commit_count,
        commit_hash=commit_hash,
        dirty=dirty,
    )
```
