### ISSUE TITLE
Release 20.5

### ISSUE THREAD

**Issue by di** [pypa/packaging#345]
This would include:
* Support PEP 600 tags (#293)
* a bugfix (#294)
* the deprecation warnings for `LegacyVersion`/`LegacySpecifier` (#342)
* New macOS tags (#319)

**Comment by pradyunsg** [comment]
https://github.com/pypa/packaging/blob/master/docs/development/release-process.rst

Who wants to cut the release? I'm happy to do so later today, if no one else intends to. :)

**Comment by pradyunsg** [comment]
Let's also include #344, and then I'll cut the release. :)

**Comment by di** [comment]
#344 has been merged, thanks!

**Comment by pradyunsg** [comment]
ACK. I'll make a release sometime this week. :)

**Comment by mattip** [comment]
@pradyunsg ping?

**Comment by yoav-orca** [comment]
@pradyunsg do you plan to release soon?

**Comment by di** [comment]
I think Pradyun is probably pretty busy with the upcoming pip release, and I doubt additional notifications from this issue is going to help.

Might be time to add some release automation via https://github.com/pypa/gh-action-pypi-publish to make this process simpler in the future.

**Comment by pradyunsg** [comment]
I'll come around to this this week -- I plan to include this in the upcoming pip release too. :)

**Comment by brettcannon** [comment]
@di see #339. 😁

**Comment by pradyunsg** [comment]
It's up! https://pypi.org/project/packaging/20.5/

Now, to update pip's vendoring and prepare for pip 20.3! :)

**Comment by pradyunsg** [comment]
I'm cutting 20.6 now, to accomodate for #357 (basically a release with #358 and a changelog entry).

**Comment by pradyunsg** [comment]
Ohkie -- I did a boo-boo and needed to yank packaging 20.6.

packaging 20.7 has been released and you can see the fun stuff in the git graph for the release tags. #359 will help prevent mistakes like this one in the future. :)
