### ISSUE TITLE
pypy2 GitHub Action is not running

### ISSUE THREAD

**Issue by pquentin** [pypa/packaging#348]
I was exploring PyPy support in GitHub Actions, and realized that PyPy for Python 2.7 isn't running as nox isn't finding the PyPy2 interpreter: https://github.com/pypa/packaging/runs/1340846724. The same issue exists for Windows and macOS. Once it's fixed, you probably want to use `--error-on-missing-interpreters` to avoid this issue in the future.

**Comment by pradyunsg** [comment]
Thanks @brettcannon!
