### ISSUE TITLE
LICENSE file is missing in 20.5 pypi release

### ISSUE THREAD

**Issue by priv-kweihmann** [pypa/packaging#357]
```
# cat packaging/__init__.py
# This file is dual licensed under the terms of the Apache License, Version
# 2.0, and the BSD License. See the LICENSE file in the root of this repository
# for complete details.
```
but named file is not shipped with packaging-20.5.tar.gz.
That was different for 20.4 releases

**Comment by pradyunsg** [comment]
Oooo. Nice catch!

We're probably want to add this in using flit's `sdist` section: https://flit.readthedocs.io/en/stable/pyproject_toml.html#sdist-section. PRs welcome! ^>^
