### ISSUE TITLE
Change default branch name to main

### ISSUE THREAD

**Issue by pradyunsg** [pypa/packaging#362]
Well, most of the non-PyPA projects I'm working on do this. If no maintainer is opposed to this, I'd like to move this project over as well.

**Comment by brettcannon** [comment]
I was just waiting for GitHub's promised renaming tool to move everything over. 😄

**Comment by pradyunsg** [comment]
Works for me! :)

**Comment by pradyunsg** [comment]
https://github.blog/changelog/2021-01-19-support-for-renaming-an-existing-branch/

It’s happened!

**Comment by brettcannon** [comment]
Do we want to set a date or just do it ASAP? @di @dstufft ? (I'm assuming this isn't controversial to do among the four of us.)

**Comment by di** [comment]
+1 from me to just do it now.

**Comment by pradyunsg** [comment]
Yea, let's just do it now. :)

**Comment by di** [comment]
Done.
