### ISSUE TITLE
20.7 tag has no corresponding Github Release?

### ISSUE THREAD

**Issue by anthrotype** [pypa/packaging#364]
two days ago a https://github.com/pypa/packaging/releases/tag/20.7 tag was pushed, however the latest release on Github is still showing as 20.4
see https://github.com/pypa/packaging/releases/latest

it would be nice if you also created a Github Release whenever a tag is pushed and package is released on PyPI.
Thank you

**Comment by pradyunsg** [comment]
Fixed. Seems like those tags needed to be annotated.
