### ISSUE TITLE
legacy setup.py support in the release tarball

### ISSUE THREAD

**Issue by priv-kweihmann** [pypa/packaging#369]
When building with e.g. YOCTO project a setup.py is required.
Since release 20.5+ this project doesn't ship one any more.
Please include at least this legacy interface to enable this use case (as several other projects already did)

**Comment by sinoroc** [comment]
Duplicate https://github.com/pypa/packaging/issues/363?

**Comment by priv-kweihmann** [comment]
Partially yes, but the referenced ticket goes way beyond what I request here

**Comment by FFY00** [comment]
This should be fixed now in master.

**Comment by brettcannon** [comment]
This is covered by the fix for #363 which was just merged.

Do note, though, that long-term relying on `setup.py` will break and one should work towards supporting PEP 317 (we are currently expecting to do this change in about a year's time for our 2022 release).

**Comment by FFY00** [comment]
Typo, there Brett meant PEP 517, not 317 :stuck_out_tongue:

**Comment by sinoroc** [comment]
@FFY00 @brettcannon Maybe it is worth reaching out to _yocto_ people and see if they want to follow and participate in the [conversation on this topic](https://discuss.python.org/t/pep-517-workflow-for-distributions/5959) as well. I don't think I have seen yocto mentioned in that context yet. Or maybe it just not meaningful to them, I don't know how yocto works. 

@priv-kweihmann Are you somehow involved in the packaging of Python projects for yocto?

**Comment by moto-timo** [comment]
@FFY00 thank you for reaching out on [IRC](https://www.yoctoproject.org/irc/%23yocto.2020-12-05.log.html). I am one of the main Python people in the Yocto world (creator of [meta-python](http://layers.openembedded.org/layerindex/branch/master/layer/meta-python/)). I am also the maintainer of the python3-packaging recipe (which we just moved into [openembedded-core](https://git.openembedded.org/openembedded-core/tree/meta/recipes-devtools/python/python3-packaging_20.4.bb)). I'll attempt to get caught up in the discussion.

**Comment by moto-timo** [comment]
FWIW, I have begun the Yocto Project support for [PEP 517](http://git.yoctoproject.org/cgit/cgit.cgi/poky-contrib/log/?h=timo/python-pep-517).

This will require a new bbclass instead of [setuptools3](http://git.yoctoproject.org/cgit/cgit.cgi/poky/tree/meta/classes/setuptools3.bbclass) or [distutils3](http://git.yoctoproject.org/cgit/cgit.cgi/poky/tree/meta/classes/distutils3.bbclass) (or some kind of flag/option/config).

Thanks to @FFY00 on [IRC](https://www.yoctoproject.org/irc/%23yocto.2020-12-05.log.html) I think I understand enough of how this could/should work to get there. Or at least we will be ready for when pypa/installer is a thing :1st_place_medal:

**Comment by dtantsur** [comment]
> Do note, though, that long-term relying on setup.py will break and one should work towards supporting PEP 317

Please note that many of us are stuck with older versions of pip/setuptools and co (hello CentOS), removing setup.py breaks us:
```
Collecting packaging===20.7 (from -c /tmp/requirements/upper-constraints.txt (line 321))
  Downloading https://files.pythonhosted.org/packages/16/7c/33ae3aa02eb10ca726b21aa88d338e3f619c674e4fb8544eb352330d880a/packaging-20.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib64/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-_s608lq8/packaging/setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-_s608lq8/packaging/
You are using pip version 9.0.3, however version 20.3.1 is available.
```

**Comment by di** [comment]
@dtantsur In that case you'll also need to use older releases of this library as well.

**Comment by dtantsur** [comment]
@di, just to confirm: should we cap `packaging<=20.5` in OpenStack while we still support things like CentOS 8 and Debian Buster? Won't it cause us problems with newer releases of other packages, especially ones like pip?

**Comment by uranusjr** [comment]
Maybe you can use `packaging!=20.5,!=20.6,!=20.7`? These should be the only three versions published with Flit.

**Comment by dtantsur** [comment]
That's what we're going to do now, but I'm trying to figure out a path forward given that `setup.py` support is apparently not eternal.
