### ISSUE TITLE
Release 20.8

### ISSUE THREAD

**Issue by brettcannon** [pypa/packaging#374]

**Comment by brettcannon** [comment]
@pradyunsg releasing now seems to require GPG tag signing which I don't have set up.

**Comment by brettcannon** [comment]
I found my GPG key, so I can give this another go.

**Comment by brettcannon** [comment]
Well, the darn GPG signing was still a pain since it turns out fish and git didn't want to play nicely together to get GPG to prompt me for my passphrase. After running `nox -s release` under bash everything went smoothly.

**Comment by pradyunsg** [comment]
Wheee. Sorry for making you deal w/ GPG whiz. Feel free to drop that if you don’t think it’s important. :)
