### ISSUE TITLE
Tag macosx_10_9_universal2 not accepted when running native arm64 (on macOS 11)

### ISSUE THREAD

**Issue by rluce** [pypa/packaging#379]
**Environment**

- MacBook Pro with M1 chip
- Released Python 3.9.1 universal2 installer
- Latest pip, setuptools and wheel

**Description**

Running the arm64 portion of Python 3.9.1 to install a universal2 binary wheel ("macosx_10_9_universal2" is the default tag) fails.  On contrary, using the x86_64 portion of the very same binary the installation succeeds.  For me the expected behaviour is that such wheels can be installed with both the arm64 and x86_64 portions on macOS 11.

The offending portion that pip rejects is the `10_9` part.  If I manually rename this portion of the wheel file to `11_0`, the installation succeeds.  Again, for me the expected behaviour is that such wheels can be installed on macOS 11

**What did you want to do?**

Install a universal2 binary wheel on macOS 11 using Python 3.9.1. Simplified setup using a dummy wheel:

```
% touch asdf-1.0.0-cp39-cp39-macosx_10_9_universal2.whl 
% python -m pip install asdf-1.0.0-cp39-cp39-macosx_10_9_universal2.whl 
```

**Output**

```
ERROR: asdf-1.0.0-cp39-cp39-macosx_10_9_universal2.whl is not a supported wheel on this platform.
```

**Additional information**

Using the x86_64 portion, the wheel tag is accepted (and we get the expected error from using a dummy wheel):

```
% arch -x86_64 python -m pip install asdf-1.0.0-cp39-cp39-macosx_10_9_universal2.whl
Processing ./asdf-1.0.0-cp39-cp39-macosx_10_9_universal2.whl
[ ... ]
zipfile.BadZipFile: File is not a zip file
```

Version of the interpreter, showing that the system platform matches the wheel tag:
```
(Python 3.9.1 (v3.9.1:1e5d33e9b9, Dec  7 2020, 12:44:01) 
[Clang 12.0.0 (clang-1200.0.32.27)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sysconfig; sysconfig.get_platform()
'macosx-10.9-universal2'
```

Version of installed packages:
```
pip        21.0.dev0
setuptools 51.1.1
wheel      0.36.2
```

**Comment by pradyunsg** [comment]
How are you getting the 10_9 tag for the universal2 wheel?

**Comment by rluce** [comment]
For the actual wheel I was looking at:  I was building it through the standard toolchain `python setup.py bdist_wheel`, using the exact same Python interpreter.  It would take me a while to construct a minimal source example though.

**Comment by rluce** [comment]
That said, getting the 10_9 platform tag was my expectation -- I wanted a binary wheel whose x86_64 portion would be compatible down to macOS 10.9 and whose arm64 portion would run on all supported versions too (which currently only is 11.X...)

**Comment by ronaldoussoren** [comment]
> How are you getting the 10_9 tag for the universal2 wheel?

Using a recentish version of wheel and the universal2 build of CPython.  I don't have a link to the relevant PR at hand, but the basic idea is that a "macosx_10_9_universal2" wheel will work on all mac systems with an x86_64 or arm64 CPU running macOS 10.9 or later.

**Comment by pradyunsg** [comment]
Ah.

No one has updated packaging.tags for this change in CPython yet, so I'd request someone familiar with the situation to go ahead and file a PR for this.  :)

**Comment by ronaldoussoren** [comment]
> No one has updated packaging.tags for this change in CPython yet, so I'd request someone familiar with the situation to go ahead and file a PR for this. :)

I would have expected that  https://github.com/pypa/packaging/pull/319  would have done the trick, but apparently not. I just received my M1 system and am currently geeking on on configuring it. 

What I don't quite understand is that ``pip install pyobjc-core`` tries to build from source, while ``pip install --only-binary :all: pyobjc-core`` does use the universal2 binary wheel, but only the "macosx_11_0_universal2" wheel for PyObjC 7.0.1 and not the "macosx_10_9_universal2" one for PyObjC 7.1. 

I guess its time to clone the repo and try to understand what's going on here.

**Comment by pradyunsg** [comment]
We're basically using the tags from this package as-is. Running `pip debug -v` will print the list of tags that pip tries to use with wheels.

**Comment by ronaldoussoren** [comment]
``pip debug -v`` shows that pip only looks at 11.0 wheels (as was to be expected given this issue).

**Comment by ronaldoussoren** [comment]
The attached PR should fix the issue. When I replace the copy of packaging in pip._vendor by the patched version in the PR "pip debug -v" shows the expected output and "pip install pyobjc-core" uses the universal2 wheel to install.

**Comment by henryiii** [comment]
Independently discovered by @joerick in https://github.com/joerick/cibuildwheel/pull/484 as well.
