### ISSUE TITLE
Is an empty string a valid LegacyVersion?

### ISSUE THREAD

**Issue by uranusjr** [pypa/packaging#382]
From https://github.com/pypa/pip/pull/9405#issuecomment-753482329

Current pip allows a user to specify requirements like `packaging==`. `packaging` parses the part after `==` as a `LegacyVersion` containing an empty string. Whether this is a bug or not, depending on how far the “LegacyVersion can contain anything” idea is taken, but the behaviour is quite confusing to both users.

Since distutils and setuptools both use `0.0.0` if a package is built without specifying a version (or an empty one), it is reasonable to disallow `LegacyVersion("")` IMO.

**Comment by pradyunsg** [comment]
Let's do this. :)

**Comment by pfmoore** [comment]
Note that even if `LegacyVersion("")` is considered valid, I'd still consider there to be a question about whether a specifier of bare `==` should be allowed. PEP 440 states that "A version matching clause includes the version matching operator == and a version identifier", and it feels to me that `==` is missing the "version identifier" part. The PEP doesn't cover legacy versions (so in terms of the PEP an empty version is invalid), so it's not a conformance issue, but I feel that allowing a bare comparison operator goes against the spirit of the PEP.

**Comment by pfmoore** [comment]
Actually, what's the timescale for the next major release of the project, because it appears that `LegacyVersion` is due to be removed (see [here](https://github.com/pypa/packaging/blob/master/packaging/version.py#L127))...

**Comment by pradyunsg** [comment]
Anytime this year. ;)

packaging also follows a CalVer cadence.

**Comment by pfmoore** [comment]
More to the point, then, I guess there's no reason to disallow "" as a `LegacyVersion`, because the same release that does that will also remove `LegacyVersion` (or am I reading too much into the statement "creating a LegacyVersion has been deprecated"?)

**Comment by pradyunsg** [comment]
https://github.com/pypa/packaging/issues/321#issuecomment-659329014

No, you're right. This project will drop Legacy Version very soon, and we probably don't need to fix this code before removing it.

**Comment by brettcannon** [comment]
More reason to drop `LegacyVersion` then! 😁

**Comment by pradyunsg** [comment]
See https://github.com/pypa/packaging/pull/407 for the discussion. Basically, I didn't have time for the PR removing, and that resulted in not removing legacy in the first release.

**Comment by hrnciar** [comment]
> Could you file a new issue for the hand written parser for PEP 508 against this repo?

Sure thing, see #468
