### ISSUE TITLE
Simplify calling nox in the GitHub Actions workflow

### ISSUE THREAD

**Issue by brettcannon** [pypa/packaging#384]
I _think_ if we change how we call nox in https://github.com/pypa/packaging/blob/master/.github/workflows/test.yml to do `--python python --extra-python python` **and** PyPy is getting symlinked as `python`, then we can drop the special-casing for PyPy and just run the `tests` session with those extra flags.

**Comment by strokirk** [comment]
This issue seems to be resolved by https://github.com/pypa/packaging/commit/705d1743ca94ba31af9828ec83f5dca77ee1b238

**Comment by pradyunsg** [comment]
Indeed! Thanks @strokirk!
