### ISSUE TITLE
Wrong version comparison

### ISSUE THREAD

**Issue by videns** [pypa/packaging#386]
Use packaging.version.parse to compare software version. Have found such problem with openssl versions:

```from packaging import version as pckVersion
a = pckVersion.parse("1.1.1i")
b = pckVersion.parse("1.0")
b > a
True
```

**Comment by uranusjr** [comment]
`1.1.1i` is not a valid PEP 440 version, so comparison against `version.Version` should either fall back to `LegacyVersion` or return `NotImplemented`. But with `LegacyVersion` being deprecated, this is probably not worth fixing.

**Comment by pradyunsg** [comment]
See also the issues linked in (and discussion at) https://github.com/pypa/packaging/issues/321.
