### ISSUE TITLE
Consider dropping (the "required" state for) Travis?

### ISSUE THREAD

**Issue by brettcannon** [pypa/packaging#395]
Personal experience with CPython says all CI fails, so you either don't require any of them or you stick with one and deal with its shortcomings rather than dealing with N tools' shortcomings.

Travis is currently not returning any status and since it's required I can't merge any PRs without an admin override. I'm personally fine just going with GitHub Actions as I don't think Travis adds much benefit. But if people want to keep it then can we consider changing the status check requirement for it?

**Comment by di** [comment]
Something odd is going on with our Travis-CI account:

> Builds have been temporarily disabled for private and public repositories due to a negative credit balance. Please go to the Plan page to replenish your credit balance.

![image](https://user-images.githubusercontent.com/294415/106537030-25c30100-64bf-11eb-9a3c-7b939e4f2713.png)

(cc @ewdurbin)

**Comment by di** [comment]
If we're fully ported to GitHub Actions, I don't see any reason to continue using Travis here (especially if we're consuming credits that other PyPA projects may actually need more than us).

**Comment by pradyunsg** [comment]
I'd say let's just take out Travis CI.

**Comment by brettcannon** [comment]
I think the IRC integration is the only thing we are missing, otherwise we actually have integrated with GHA than Travis at this point.

I have gone ahead and turned off the webhook to see how this goes. If it works out then we can delete the hook, `.travis.yml` and ask someone to remove the Travis integration (I don't appear to have the appropriate permissions; maybe org admin can do it?).

**Comment by pradyunsg** [comment]
Given that I have travis-ci muted in IRC, I don't think anyone cares about that integration at this point. :)

Your plan sounds great to me!

**Comment by brettcannon** [comment]
I've tweaked the status check requirements to only be GHA so that we control it while we see how this goes. I say we give it a month, and if it works out then we can drop Travis.

**Comment by mayeut** [comment]
Does anybody here have a clue what's happening with our Travis-CI account or if there's someone in charge of that account ?
I guess we had some (maybe free) credits credited every day/month since travis-CI changed its policy and up-until end of January but that stopped for some reason ?
Happy to take this discussion elsewhere but I'm not sure discuss.python.org is appropriate.

**Comment by di** [comment]
It looks like on Jan 29th, Travis switched us to a free plan with 10K build credits, but we're currently in a hole of -930 credits that we're not recovering from. I reached out to support.

**Comment by di** [comment]
The PyPA travis account has been temporarily restored, but I'd still encourage this project (and others) to migrate to Actions.

**Comment by mayeut** [comment]
Thanks for the feedback @di 
Could you expand a bit on "temporarily" ?

pypa/manylinux & pypa/auditwheel could really benefit from travis-ci for `aarch64`/`ppc64le`/`s390x` where those architectures are natively supported (using qemu on GHA works but gives a build time of nearly 5 hours vs 30-40 minutes on travis-ci).

**Comment by di** [comment]
@mayeut We're currently paying for a paid plan and waiting to see if we'll get renewed credits. The PSF is currently footing the bill but I think we can ensure that we don't pull the rug out from under pypa/manylinux and pypa/auditwheel as long as there isn't a better alternative.

My encouragement is for projects like pypa/packaging that don't really _need_ to be on Travis vs. another CI provider, and can help us reduce the overall Travis usage by migrating.

**Comment by brettcannon** [comment]
Then I'm up for cutting off Travis now instead of waiting until the end of the month.

**Comment by di** [comment]
FWIW this is the usage breakdown over the two months:

![image](https://user-images.githubusercontent.com/294415/107438977-fd5a8880-6af6-11eb-865a-ffdfb96e1911.png)

**Comment by brettcannon** [comment]
At least we are the cheap one. 😉

**Comment by pradyunsg** [comment]
Hmm... Is there something from pip still on Travis CI?

Last I checked, every pip commit resulted in upto ~15 hours of machine time across our various workers.

**Comment by di** [comment]
> Hmm... Is there something from pip still on Travis CI?

@pradyunsg looks like yes: https://travis-ci.com/github/pypa/pip/builds

**Comment by brettcannon** [comment]
So, drop Travis?

**Comment by pradyunsg** [comment]
Yup.

**Comment by ewdurbin** [comment]
OK, I think that's done!

**Comment by brettcannon** [comment]
Thanks @ewdurbin ! And with https://github.com/pypa/packaging/commit/6b659abf0377fad9c0b6a48e5ba80a32b0b1d6f6 I think we are all cleaned up!

**Comment by pradyunsg** [comment]
> @pradyunsg looks like yes: https://travis-ci.com/github/pypa/pip/builds

FYI: This got removed 2 months ago -- https://github.com/pypa/pip/pull/9759
