### ISSUE TITLE
Unable to specify a VCS-via-file URL

### ISSUE THREAD

**Issue by uranusjr** [pypa/packaging#412]
Say I have a Git repoitory locally on `/path/to/repo`, it is currently not possible to specify a package in it:

```pycon
>>> from packaging.requirements import Requirement
>>> Requirement("mypackage @ git+file:///path/to/repo")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "packaging/requirements.py", line 130, in __init__
    raise InvalidRequirement("Invalid URL: {0}".format(req.url))
packaging.requirements.InvalidRequirement: Invalid URL: git+file:///path/to/repo
```

This is because the `Requirement` class currently ensures the URL contains `netloc`:

https://github.com/pypa/packaging/blob/456f94fc0aacaaf3d5da6e833e8043c3e5ce1c2b/packaging/requirements.py#L114-L117

IMO the class should not perform any validation, since PEP 508 does not in any restrict what qualifies as a URL, and any decision on what URLs to support falls entirely on the caller. At the very least, it should allow the caller to provide a custom validator.

**Comment by sbidoul** [comment]
Yeah, that's an oldie: https://github.com/pypa/packaging/pull/264.

**Comment by uranusjr** [comment]
🤦
