### ISSUE TITLE
CalVer?

### ISSUE THREAD

**Issue by hugovk** [pypa/packaging#426]
Does packaging follow [CalVer](https://calver.org/)?

If so, I guess the last release from Jan 29, 2021 should have really been 21.0 instead of 20.9?

* https://pypi.org/project/packaging/20.9/
* https://packaging.pypa.io/en/latest/changelog.html

I don't think that's necessarily a problem, rather this is a prompt for the _next_ one to be 21.0 :)

And maybe add some checks to the release checklist/scripts?

**Comment by pradyunsg** [comment]
It's definitely going to be a 21.0 release. It's just that we've not made progress on certain blockers for that release.

**Comment by brettcannon** [comment]
And the `20.9` release was on purpose due to being made for pip's behalf and having some compatibility with Python 2.7.

**Comment by hugovk** [comment]
All good, I don't think we need to keep this issue open. Thank you!
