### ISSUE TITLE
Release 20.10

### ISSUE THREAD

**Issue by dHannasch** [pypa/packaging#439]
Are there any plans for when Release 20.10 might be? Asking mainly because `pip` will be able to turn on support for musl wheels for everyone as soon as `packaging` cuts a release, since the support is already in the `packaging` main branch.

(https://hub.docker.com/orgs/pythonpackagesonalpine/repositories is already successfully building some Alpine images using musl wheels, using a hacked version of `pip` with the main branch of `packaging`. Of course, once musl wheels are fully supported and start getting published, there will be no more need for https://hub.docker.com/orgs/pythonpackagesonalpine/repositories.)

**Comment by uranusjr** [comment]
I think it should be 21.0, but yes, a release for pip 21.2 would be very desired indeed. The pip release will happen sometime next month, so it would be best if packaging could have a release in a week or so.

**Comment by MrMino** [comment]
Is there anything specific needed for this to happen (i.e. something we can help with), or is it just the question of putting the release together?

**Comment by brettcannon** [comment]
@MrMino as long as there are no open PRs or issues that we feel needs to go in, then it's simply a matter of cutting the release.

**Comment by puetzk** [comment]
The other thing I would really want in pip 20.2 is the distutils -> sysconfig migration, both to fix deprecations coming in cypthon 3.10.0 (#433) and to fix wrong-wheel bugs currently occurring on windows when the vcvars environment is set (pypa/pip#8649).

Which was implemented in #396, and is already merged to `main`, so "simply a matter of cutting the release" would cover both of these issues.

**Comment by brettcannon** [comment]
I think a 21.0 release should probably contain:
1. https://github.com/pypa/packaging/pull/438
2. https://github.com/pypa/packaging/pull/407

**Comment by brettcannon** [comment]
We've decided to  postpone #407 in the name of time for the  next pip release, so I think we can release as soon as anyone has time to cut a release (although if someone wants to help by making sure the changelog is up-to-date that would be appreciated).

**Comment by puetzk** [comment]
Here's 3 items that seem changelog-worthy to me

```rst
* Fixed ``~=`` Specifier checks which include prerelease suffix to match PEP440 (:issue:`100`)
* Replace use of deprecated ``distutils`` with ``sysconfig`` to support Python 3.10 (:issue:`433`)
  This also fixes cpython_tags returning wrong values when VSCMD_ARG_TGT_ARCH is set
  (i.e. when vcvarsall has configured the environment to have MSVC cross-compiling)
  and the target architecture is different than the python.exe being run (:issue:`327`)
* Introduce platform tag for musllinux (PEP 656)
```

**Comment by pradyunsg** [comment]
I'll do this today.

**Comment by pradyunsg** [comment]
Done! https://pypi.org/project/packaging/21.0/

**Comment by pradyunsg** [comment]
Oh, and we needed at least 2 fixes to the release pipeline stuff, since we've dropped Python 2 support:

- 38aa73aee7b46eb0787ba80cb8cd3bef79dd94b2
- 093e24f29bc6ce0bd3448d63615b68d584a0cd6b
