### ISSUE TITLE
provide a mypyc sped up version of the package

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pypa/packaging#442]
for general speed up and potentially faster import this might be a nice to have

for context - i want to try and standardize setuptools_scm to provide Version instances in packages for  version comparison/checking,
for that to be nicely attainable it needs to be very inexpensive to import/use the Version class

**Comment by domdfcoding** [comment]
How much speed increase are you looking for? For me it seems pretty quick to import and parse a version as is (~25-30 ms vs ~15-20 ms to start the interpreter). Or is the issue more in the comparisons being slow?

**Comment by brettcannon** [comment]
For cheaper import, @uranusjr has proposed breaking this project up into a namespace package for more fine-grained installation.

**Comment by uranusjr** [comment]
I think the import is already as cheap as it can be and namespace modules won't add much, if any.

**Comment by RonnyPfannschmidt** [comment]
the imports themselves are already cheap.

also i figured that mypyc seems not yet suitable for more general speedup (too many missing features)

currently i doubt providing cythonized versions of simple modules is a reasonable gain, i beleive we can close this off until the idea comes up again with better surrounding tooling
