### ISSUE TITLE
Version should be iterable

### ISSUE THREAD

**Issue by amogorkon** [pypa/packaging#445]
Version() should be iterable so that it can easily be cast to a tuple and compared to sys.version_info.

**Comment by uranusjr** [comment]
I don't think it's a good idea. Python explicitly defines a version to contain three number segments (plus two suffix segments IIRC), but PEP 440 allows _unlimited_ number segments, so a conversion to tuple would produce subtly confusing result between say `1.1a1` and `1.1.1.1b2`.

**Comment by brettcannon** [comment]
I agree with Tzu-ping. Plus it wouldn't properly handle the release level for the `sys.version_info` case.

But you already have https://packaging.pypa.io/en/latest/version.html#packaging.version.Version.release which gives you a tuple that you can either use or build off of to get a tuple for comparing.

**Comment by amogorkon** [comment]
Well, the cleanest solution overall in my opinion would be to make a new VersionDigit class to provide comparability for each part.
Then you would compare a tuple of (VersionDigit("1"), VersionDigit("1a1")) with (VersionDigit("1"), VersionDigit("1"), VersionDigit("1"), VersionDigit("1b2")) with no ambiguities because you'd control `__lt__`.
