### ISSUE TITLE
Classes like Version should accept objects of the given type in their constructor

### ISSUE THREAD

**Issue by pfmoore** [pypa/packaging#454]
To ensure a value is a `Version`, it would be nice to simply be able to do `ver = Version(ver)`. But the `Version` constructor only accepts strings as arguments, so this doesn't work, you need

```python
if not isinstance(ver, Version):
    ver = Version(ver)
```

instead. It would be a lot simpler if the constructor accepted `Version` objects (and just returned them unchanged, as they are immutable).

The same issue occurs in all classes in the library - `Requirement`, `Specifier`, `SpecifierSet`, all have the same behaviour (and probably others, I didn't check).

**Comment by brettcannon** [comment]
I'm personally not a fan of this style of initializer.

@pradyunsg do you have an opinion?

**Comment by pfmoore** [comment]
I can understand that position, although the precedent of things like `int` and `str` makes it feel reasonable to me. The reason this came up (again) for me was that I was writing classes using `attrs`, and I wanted to auto-convert strings to versions. The "obvious" approach for this is

```
version: Version = attrs.field(converter=Version)
```

This follows the example in the `attrs` documentation, using `converter=int`. But with `Version`, doing this makes assigning an actual `Version` object fail.

It's not hard to work around using `converter=lambda v: v if isinstance(v, Version) else Version(v)`, (or a named function that does this) but it's a little clumsy (and annoying when I have a lot of such fields, which I do in my particular example). And actually, a utility like

```python
def convert_to(cls):
    """Use as attr: Class = field(convert=convert_to(Class))"""
    def _convert(val):
        if isinstance(val, cls):
            return val
        return cls(val)
    return _convert
```

would work beautifully, except that mypy gets extremely upset at something this dynamic 🙁 So if pressed, I would admit that I only really need this because of the limitations of mypy...

Other languages have the idea of "value types" and this type of constructor is fairly normal for value types. I feel that the types in `packaging` are essentially value types in this sense.

**Comment by pradyunsg** [comment]
I’m fine with an `ensure_parsed_version` utility being provided, but I think I feel similarly to @brettcannon about the constructor’s behaviour.

**Comment by pfmoore** [comment]
OK, if that's the consensus then let's drop the idea. I don't think `ensure_parsed_version` is worthwhile, it's easy enough to write for yourself if you need it.
