### ISSUE TITLE
Inconsistent fourth digit parsing

### ISSUE THREAD

**Issue by ShadowJonathan** [pypa/packaging#455]
A package i help maintain has a four-digit version number it uses for versioning, lets just say `1.2.3.4`.

When throwing this in `packaging.version.parse`, out comes a `Version` object which specifies that `.epoch` is `4`.

When i initially learned this, i was a little alarmed, as i knew epoch to be in the following variant; `4!1.2.3`, so i was afraid that this was recognising a number at the end of the indicator as higher than all the numbers before it.

Playing around a bit with how `packaging` recognises this, i saw that it just works like normal, and sees the 4th digit as "just" another "lower-than-micro" number.

However, when putting in a 5-digit version number, `1.2.3.4.5`,`.epoch` was `0`, indicating that the fourth digit wasn't, at least, consistently parsed.

---

1. Is the fourth digit parsing as epoch correct here?

2. How should this inconsistency with parsing the fourth digit as an epoch, between parsing a 4-digit version and a 5-digit version, be resolved?

**Comment by pradyunsg** [comment]
```py
>>> import packaging
>>> packaging.__version__
'21.0'
>>> from packaging.version import Version
>>> v1 = Version("1.2.3.4")
>>> v1.epoch
0
>>> from packaging.version import parse
>>> v2 = parse("1.2.3.4")
>>> v2
<Version('1.2.3.4')>
>>> v2.epoch
0
>>> v1 == v2
True
```

I'm unable to reproduce the reported behaviour.

**Comment by ShadowJonathan** [comment]
Ah, i was running `packaging` 20.4, sorry for the confusion.
