### ISSUE TITLE
feature request: Version comparison with str ?

### ISSUE THREAD

**Issue by neutrinoceros** [pypa/packaging#465]
Would it make sense to add support for direct comparison between `Version` objects and `str` ?
Currently when using `packaging.version.Version` to write 'versioned code branches' to support multiple versions of a third party package (e.g. `foo`), one need to import the `Version` class everywhere versions are being compared, which means that each module needs to import and parse the version for `foo`, or import it from a common module (say `a.py`), and import `Version`.

```python
# a.py
import foo
from packaging.version import Version

FOO_VERSION = Version(foo.__version__)

# b.py
from .a import FOO_VERSION
from packaging.version import Version

if FOO_VERSION >= Version("2.0"):
    ...
else:
    ...
```

Now say the `Version` class knows how to compare with `str` directly, the `b.py` module could be simplified as

```python
# b.py
from .a import FOO_VERSION

if FOO_VERSION >= "2.0":
    ...
else:
    ...
```
now multiply this by dozens of modules and more branches, and this noticeably alleviates the maintenance cost of these branches.

I would like to offer such a contribution, but is this something people other than me are interested in ?

**Comment by uranusjr** [comment]
#454 would kind of help with this as well since you'd always call `Version` instead and at least don't need to remember the type of `FOO_VERSION`.

**Comment by hmaarrfk** [comment]
Would you consider, as an exception to your rule, to allow comparisons to strings, but to emit a warning? This would greatly help in the transition away from distutils.

I've been hit by a few bugs that we couldn't catch in our CI procedure migrating away from distutils.

**Comment by brettcannon** [comment]
@hmaarrfk can you share the code? I don't quite understand how this would help with a distutils migration.

**Comment by hmaarrfk** [comment]
```python
In [1]: from distutils.version import LooseVersion as Version

In [2]: Version('1.2.0') > '1.1.19'
<ipython-input-2-a0e8c8992dad>:1: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  Version('1.2.0') > '1.1.19'
True

In [3]: from packaging.version import Version

In [4]: Version('1.2.0') > '1.1.19'
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-a0e8c8992dad> in <module>
----> 1 Version('1.2.0') > '1.1.19'

TypeError: '>' not supported between instances of 'Version' and 'str'
```

**Comment by hmaarrfk** [comment]
In this example, it is obvious that `'1.1.19'` is a string. However, in python, it is often hard to inspect things in detail.

Therefore, I would want this `TypeError` to issue a warning instead, guiding users through the migration path.

Typically you achieve this with:
```
warn(..., stacklevel=2)
```
pointing to the user's line of code that should be changed.

**Comment by pradyunsg** [comment]
> to issue a warning instead,

And how should it behave? If it is still erroring out, then presenting that warning isn't particularly useful.

And if the new behaviour involves coercing the string or anything other than erroring out, then we're (a) introducing a backwards-incompatible behaviour change and (b) see the rationale provided above for not doing this.

If you absolutely want things to behave like distutils' `LooseVersion`, feel free to create a subclass of `packaging.version.Version` that overrides the comparision operators to behave how you want, and using that subclass instead.

**Comment by hmaarrfk** [comment]
> introducing a backwards-incompatible behaviour change

I'm not sure where backward incompatibility was discussed. That said, I understand the importance of that.

> If you absolutely want things to behave like distutils' LooseVersion, feel free to create a subclass of packaging.version.Version that overrides the comparision operators to behave how you want, and using that subclass instead. I don't see any way to provide that functionality within the constraints we're operating in.

This is a very fair point, and definitely makes things easier from `packaging`'s point of view. I understand (though, I don't entirely agree with) your decision to take this approach.


My main objection to not allowing comparisons to string is that code that depends on version comparison might be locating in a compatibility shim. This makes it extremely hard to test on CIs where quite often, strange package combinations don't exist. Often developers test against:
    * The lowest dependencies allowed.
    * The latest available versions of all packages.
    * Nothing in between.
This means that the only time you actually test for these kinds of comparisons is in the wild. 

The recommendation to use `packaging.version.Version` to replace `distutil`'s `LooseVersion` is thus, in my opinion, not very maintainer friendly.

**Comment by brettcannon** [comment]
> The recommendation to use packaging.version.Version to replace distutil's LooseVersion is thus, in my opinion, not very maintainer friendly.

I'm not sure where you're getting that warning from (maybe setuptools since that isn't in [Python's stdlib itself](https://github.com/python/cpython/blob/main/Lib/distutils/version.py)), but it isn't coming from us and this project.

**Comment by hmaarrfk** [comment]
You are right, it is setuptools:
https://github.com/pypa/setuptools/blob/main/setuptools/_distutils/version.py#L53

In either case, thank you for taking the time to respond to this issue and to reconsider.

**Comment by tony** [comment]
We use `LooseVersion`/`LegacyVersion` in a python project compared against `str`

https://github.com/tmux-python/tmuxp/blob/v1.9.4/tmuxp/plugin.py#L138-L141

`LooseVersion` in `distutils` could do this type of comparison.

@pradyunsg 

> feel free to create a subclass of `packaging.version.Version` that overrides the comparision operators to behave how you want, and using that subclass instead.

I'm interested in what that would look like, could you provide an example?  I am overriding them myself and I'm still getting the comparator error.

What we're looking for is exactly that, we want to support the official packaging but in instances where we want behavior slightly specialized, to subclass.

**Comment by layday** [comment]
```py
from functools import total_ordering

from packaging.version import Version


@total_ordering
class _VersionCmpMixin:    
    def __eq__(self, other: object) -> bool:
        if isinstance(other, str):
            other = Version(other)
        return super().__eq__(other)

    def __lt__(self, other: object) -> bool:
        if isinstance(other, str):
            other = Version(other)
        return super().__lt__(other)


class MyVersion(_VersionCmpMixin, Version):
    pass


assert MyVersion("3") == "3.0.0"
assert MyVersion("3") != "3.0.1"
```

**Comment by tony** [comment]
@layday This works wonders!  Especially with the mixin. Thank you!
