### ISSUE TITLE
Hand written parser for PEP 508 to drop dependency on pyparsing

### ISSUE THREAD

**Issue by hrnciar** [pypa/packaging#468]
Hello,

I opened this issue to let you know that I am working on a handwritten parser for PEP 508. My goal is to drop dependency on pyparsing as discussed [here](https://discuss.python.org/t/split-tags-into-a-separate-package/4965/9). It is still working in progress so I will follow up later when it's ready.

**Comment by pradyunsg** [comment]
A very gentle nudge on this @hrnciar. :)

**Comment by hrnciar** [comment]
> A very gentle nudge on this @hrnciar. :)

Thanks for the ping :), I've opened draft PR.

**Comment by nanonyme** [comment]
I'm curious what the incentive is here. Pyparsing is not problematic for bootstrapping pypa/build using native pep517 build backends. This project and pypa/build itself are the problems (and there is already open PR to convert this project to using flit)

**Comment by nanonyme** [comment]
The entire discussion in original thread seems obsolete
