### ISSUE TITLE
Support pyparsing version 3

### ISSUE THREAD

**Issue by rikardn** [pypa/packaging#481]
Version 3 of `pyparsing` was recently released and `packaging` has a block for versions from 3 and higher. The comment in setup.py seems to hint that this block was needed a long time ago. Could perhaps this block be lifted to simplify dependency resolution downstream?

**Comment by uranusjr** [comment]
Please see #480

**Comment by rikardn** [comment]
Thanks @uranusjr for the info.  (I only checked issues before posting so I missed the ongoing discussion.)

**Comment by pradyunsg** [comment]
Closed via #482

**Comment by vnmabus** [comment]
Are you going to release this fix soon? Currently my documentation build is broken because of the dependence constraint and I want to know if I need to provide a work-around or if you plan to have a release in the next few days.

**Comment by pradyunsg** [comment]
See #483

**Comment by rikardn** [comment]
Thanks for fixing this.
