### ISSUE TITLE
Parsing markers/requirements fails with pyparsing 3.0.5

### ISSUE THREAD

**Issue by 9999years** [pypa/packaging#486]
Pyparsing 3.0.5 [changes the private API around `originalTextFor`](https://github.com/pyparsing/pyparsing/commit/e269b0a3d067e66ef718b8508a4a82927c7606d0#diff-daba53cec7bed1be7b180ee5e8378c772408d07afe6f2cad6d62e966993b9e45), causing code in `packaging` that uses the private API to break:
https://github.com/pypa/packaging/blob/8cb9dbf19e2b76ab025efc11208bd50e09e8223e/packaging/requirements.py#L69-L72

This manifests as a failure in `safety`.

Reproduction:
```
from packaging.requirements import Requirement

Requirement('alabaster==0.7.12; python_version >= "3.6"\n')
```

The upstream issue is https://github.com/pyparsing/pyparsing/issues/110#issuecomment-963167729

**Comment by ptmcg** [comment]
Pyparsing 3.0.6 just released, implements warning suppression without changing results names.

May be moot in the face of other PRs, but should resolve some issues people are having with current packaging version and latest pyparsing.
