### ISSUE TITLE
Version/parse needs to be improved!

### ISSUE THREAD

**Issue by YoSTEALTH** [pypa/packaging#501]
```Python
from platform import uname
from packaging.version import Version, parse
from setuptools._distutils.version import LooseVersion 


# Packaging (failing)
# ===================
a = parse(uname().release)
print(a)
# 5.15.12-1-MANJARO

b = Version('5.10')
print(b)
# 5.10

print(a < b)
# True

# setuptools (old but good)
# =========================
a = LooseVersion(uname().release)
b = LooseVersion('5.10')
print(a < b)
# False
```

**Comment by pradyunsg** [comment]
`packaging.version` is intended for parsing versions for Python Packaging tooling, for the format specified in PEP 440.

If you're looking for arbitrary version parsing, please look for other packages on PyPI that parse arbitrary versions.

**Comment by YoSTEALTH** [comment]
Since `distutils` is being deprecated https://docs.python.org/3/library/distutils.html it was recommended to use `packaging` as mentioned https://www.python.org/dev/peps/pep-0632/#migration-advice to replace features previously provided in `distutils.version`
``` text
For these modules or types, use the standards-defined Python Packaging Authority packages specified:

    distutils.version — use the packaging package
```

**Comment by brettcannon** [comment]
We actually didn't write that advice, although for code that is being used for Python packaging it does make sense. But if you need a more generic parser like the one distutils provided then I would honestly suggest copying the code out of distutils and vendor it in your own code.
