### ISSUE TITLE
Document `markers.default_environment()`

### ISSUE THREAD

**Issue by brettcannon** [pypa/packaging#503]
https://github.com/pypa/packaging/blob/171e4fb7016383525d967b8584a591bf416dcb42/packaging/markers.py#L257-L272

The name and its inclusion in `__all__` suggest this is part of the API and should be documented.

**Comment by brettcannon** [comment]
@pradyunsg there's now a PR for this at https://github.com/pypa/packaging/pull/753 . Are you okay with making this part of the documented, public API?

**Comment by pradyunsg** [comment]
Yes.
