### ISSUE TITLE
`version.parse` compares differently than `distutils.version`

### ISSUE THREAD

**Issue by cbrnr** [pypa/packaging#514]
Because `distutils.version` is deprecated and explicitly recommends to use `packaging.version`, we've recently switched to the latter. Unfortunately, comparing versions works differently (example from https://github.com/mne-tools/mne-python/issues/10404):

```python
>>> from distutils.version import LooseVersion
>>> LooseVersion('1.0.dev0') >= LooseVersion('1.0')
<stdin>:1: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
True
>>> from packaging.version import parse
>>> parse("1.0.dev0") >= parse("1.0")
False
```

Is there something I'm missing?

**Comment by pradyunsg** [comment]
This is expected. packaging.version uses PEP 440-specified rules for comparing versions. distutils.version has its own custom logic that isn't really mirrored anywhere, as far as I know.

See https://github.com/pypa/packaging/issues/321 for the discussion on dropping `LegacyVersion` from packaging (which is closer to distutils.version, and similary wonky), and https://github.com/pypa/packaging/issues/502 and https://github.com/pypa/packaging/issues/501#issuecomment-1018979912 for other users who are also migrating away from `distutils.version`.

**Comment by cbrnr** [comment]
Thanks @pradyunsg! So we'd better update the code on our side then.
