### ISSUE TITLE
Version comparison can be incorrect when there is a + sign in the version

### ISSUE THREAD

**Issue by ajindal1** [pypa/packaging#519]
When comparing packages which contain "+" sign is not giving correct results when the version numbers are the same. For example, the output for both the below statements should have been True, but it is not.

`from packaging import version`
`version.parse("1.11.1.dev") <= version.parse("1.11.1")`                                                                                                                                                                                
True
`version.parse("1.11.1+cpu") <= version.parse("1.11.1")`                                                                                                                                                                             
False

**Comment by uranusjr** [comment]
`+` has special meaning, specifically it signifies a [local version](https://peps.python.org/pep-0440/#local-version-identifiers). And a local version is always greater than a public version with matching non-local segments. The logic is working as intended.

**Comment by uranusjr** [comment]
I’m curious though, why do you think both expressions should be True? If compared naively, a version with more segments should be greater than the one with less segments in general (e.g. `1.1.1` is always greater than `1.1`). So it’s really the `.dev` example that’s the exception, not the `+cpu` one.

**Comment by ajindal1** [comment]
Thanks for sharing the information about the local version, I believed that the 1.11.1+cpu is the same as 1.11.1 in the version comparison, I know that 1.1.1 is always greater than 1.1.

**Comment by uranusjr** [comment]
You’re not entirely wrong, `1.11.1+cpu` would indeed _satisfy `<=1.11.1`_. But this does not mean `1.11.1+cpu <= 1.11.1`; rather, the `<=` version range oeprator has special semantic subtly different from the Python `<=` operator.

In general, if you want to answer the question “does this version contained by this version range”, you should use `SpecifierSet` to perform the logic, not the comparison operators on the `Version` class. Those operators are for Python-based logic, e.g. to deterministically order versions so the best match can be selected from a list of known versions. Version logic is hard 🙂
