### ISSUE TITLE
Is there a `StrictVersion` after we drop `distutils`?

### ISSUE THREAD

**Issue by cclauss** [pypa/packaging#520]
We currently use `from distutils.version import StrictVersion` but we want to drop `distutils` in preparation for Python 3.12.  What is the recommended substitute for `StrictVersion`?  https://github.com/python/cpython/blob/main/Lib/distutils/version.py#L93

https://github.com/pypa/packaging/blob/main/packaging/version.py
* https://github.com/pypa/setuptools/discussions/3145

**Comment by brettcannon** [comment]
Our normal `Version` class is strict when it comes to Python packaging version support, so that probably covers what you want. Otherwise you can also use `packaging.utils.canonical_version()` if you want even more strict string output.
