### ISSUE TITLE
Implement PEP 685

### ISSUE THREAD

**Issue by brettcannon** [pypa/packaging#526]
https://peps.python.org/pep-0685/

- [x] Normalize `extra` comparisons
- [x] ~Update `requirements.Requirement.extras` to raise a warning when names clash~
- [x] Update docs for `packaging.utils.canonical_name()`
- [x] #495 
- [ ] #383 
- [ ] Mark the PEP as "final"?

**Comment by brettcannon** [comment]
I _think_ if we update:

https://github.com/pypa/packaging/blob/ba124324e866e518ebfe0378a25b6ba4816e5880/packaging/markers.py#L141-L145

... to coerce `extra` comparisons immediately after parsing, then that's probably the easiest way to get the value normalized (for printing, writing, etc.). Then we have to worry about comparisons, which may be in:

https://github.com/pypa/packaging/blob/ba124324e866e518ebfe0378a25b6ba4816e5880/packaging/markers.py#L189-L201

... or:

https://github.com/pypa/packaging/blob/ba124324e866e518ebfe0378a25b6ba4816e5880/packaging/markers.py#L177-L186

... or:

https://github.com/pypa/packaging/blob/ba124324e866e518ebfe0378a25b6ba4816e5880/packaging/markers.py#L233-L238

There's also separate work for requirements for the `self.extras` attribute:

https://github.com/pypa/packaging/blob/ba124324e866e518ebfe0378a25b6ba4816e5880/packaging/requirements.py#L121

**Comment by brettcannon** [comment]
Thanks to @hroncok we have a PR to normalize the comparison. I have an in-progress PR on my local machine which normalizes for the string representation of markers.

**Comment by hroncok** [comment]
BTW I am sorry for not searching for this issue first. I should have and I have no idea why I haven't :(

**Comment by brettcannon** [comment]
> BTW I am sorry for not searching for this issue first. I should have and I have no idea why I haven't :(

No worries! My in-progress PR isn't wasted regardless since the hardest part in it is normalizing at parse time for `__str__()`.

**Comment by brettcannon** [comment]
Now that `markers` normalizes everything, I don't think `requirements` needs an update for `extras`. Any issues with those fields can (eventually) be handled by `metadata`.

**Comment by ofek** [comment]
Any update on this?

**Comment by brettcannon** [comment]
I think we can declare this as done as it's going to be for now. 😁 I just pushed the docs for `packaging.utils.NormalizedName` and `packaging.utils.canonicalize_name()`. I don't think this needs to wait for anything in `packaging.metadata`.

**Comment by ofek** [comment]
Nice! Any ETA for pip to upgrade its bundled copy of this?

**Comment by brettcannon** [comment]
> Nice! Any ETA for pip to upgrade its bundled copy of this?

That's a @pradyunsg question.

**Comment by pradyunsg** [comment]
If we cut a packaging release early in this month (say, next week or so) then it'd be in pip 22.2 (due by end of month).

**Comment by ofek** [comment]
22.2 was released

**Comment by Julian** [comment]
@ofek not sure if that comment was meant to point this out too but this didn't make it into `pip` 22.2 right? Ostensibly because this repo needs a release first right @pradyunsg? Or am I misunderstanding still what's left for this one.

**Comment by Julian** [comment]
Ah, sorry to double post, but I see #569 is the ticket asking for a release, so this is still "blocked" on that on the pip side if I understand correctly.
