### ISSUE TITLE
Document exceptions raised by functions in `packaging.utils`

### ISSUE THREAD

**Issue by pradyunsg** [pypa/packaging#543]
Functions like `parse_wheel_filename` and `parse_sdist_filename` can raise exceptions, but this is not a documented detail. We should document the exceptions and add a `Raises` to the relevant functions.

**Comment by MrMino** [comment]
I'm happy to PR for this, I'm familiar with much of this. 

Let me know if I'm mistaken in any / missing something:

- `canonicalize_name` - doesn't raise
- `canonicalize_version` - doesn't raise
- `parse_wheel_filename` - raises `InvalidWheelFilename` when:
    - given filename does not end with `".whl"`
    - the number of dashes (parts) in the filename is different from 4 or 5
    - the distribution name contains unescaped non-alphanumerical characters ([PEP427 escaping and unicode](https://peps.python.org/pep-0427/#escaping-and-unicode)).
    - the build number doesn't start with a digit
- `parse_sdist_filename` - raises `InvalidSdistFilename` when:
    - given filename does not end with a sdist-appropriate extension (`.zip` or `.tar.gz`)
    - if the distribution name and version are not separated by a `-` (dash). 
    
Is there anything else? How detailed does this description needs to be?
 
_For convenience: https://packaging.pypa.io/en/latest/utils.html_

**Comment by MrMino** [comment]
I'm happy to PR for this, I'm familiar with that part. 

Let me know if I'm mistaken in any / missing something:

- `canonicalize_name` - doesn't raise
- `canonicalize_version` - doesn't raise
- `parse_wheel_filename` - raises `InvalidWheelFilename` when:
    - given filename does not end with `".whl"`
    - the number of dashes (parts) in the filename is different from 4 or 5
    - the distribution name contains unescaped non-alphanumerical characters ([PEP427 escaping and unicode](https://peps.python.org/pep-0427/#escaping-and-unicode)).
    - the build number doesn't start with a digit
- `parse_sdist_filename` - raises `InvalidSdistFilename` when:
    - given filename does not end with a sdist-appropriate extension (`.zip` or `.tar.gz`)
    - if the distribution name and version are not separated by a `-` (dash). 
    
Is there anything else? How detailed does this description needs to be?
 
_For convenience: https://packaging.pypa.io/en/latest/utils.html_
