### ISSUE TITLE
Populate marker environment with `extra` as `""` by default

### ISSUE THREAD

**Issue by pradyunsg** [pypa/packaging#548]
IMO, packaging should assume an empty list of extras by default, rather than requiring the caller to specify it explicitly

_Originally posted by @pfmoore in https://github.com/pypa/pip/issues/11112#issuecomment-1124922758_

I agree with @pfmoore. :)

**Comment by MrMino** [comment]
I believe this requires adding an empty string under the right key in `markers.default_environment`? Seems a bit too simple, what am I missing?

**Comment by MrMino** [comment]
I believe that, with this change, the `markers.UndefinedEnvironmentName` becomes redundant. It's impossible to trigger it.

The default environment already contains all of the possible marker names (checked using the code below), and the grammar set out in the module via `pyparsing` makes it impossible to use any other. [`evaluate()` doesn't seem to have a way of explicitly specifying undefined name in the environment either](https://github.com/pypa/packaging/blob/6da5d33194e85c5932c3ea67892ba19760fd0ace/packaging/markers.py#L343).

Should it be removed?

This code contains all "variable" names, and will not raise any exception:

```
from packaging.markers import Marker

names = [
    "implementation_version",
    "platform_python_implementation",
    "implementation_name",
    "python_full_version",
    "platform_release",
    "platform_version",
    "platform_machine",
    "platform_system",
    "python_version",
    "sys_platform",
    "os_name",
    "os.name",
    "sys.platform",
    "platform.version",
    "platform.machine",
    "platform.python_implementation",
    "python_implementation",
    "extra",
]
for name in names:
    Marker(f"{name} == '1.2.3'").evaluate()
```
