### ISSUE TITLE
Use of "in" / "not in" for markers

### ISSUE THREAD

**Issue by h-vetinari** [pypa/packaging#552]
I ran into an unexpected limitation while trying to refactor the following from https://github.com/scipy/oldest-supported-numpy

```
numpy==1.17.3; python_version=='3.8' and platform_machine!='arm64' and platform_machine!='aarch64' and platform_machine!='s390x' and platform_machine!='loongarch64' and platform_python_implementation != 'PyPy'
```

into the more readable

```
numpy==1.17.3; python_version=='3.8' and platform_machine not in ('arm64', 'aarch64', 's390x', 'loongarch64') and platform_python_implementation != 'PyPy'
```

based on the assumption that normal python semantics would work in the selectors. However, this crashes the parser (and similarly for "and not in")

I've tried to look around the existing issues, but nothing jumped out at me, so I'm opening a new one. Apologies if this is a subset of some larger issue that I haven't picked up on.

**Comment by uranusjr** [comment]
From the grammr, only variables and string-like expressions can appear next to a marker operator, and that’s the reason why the second expression does not work, not the operators themselves. I guess it can be approximated with `platform_machine not in 'arm64|aarch64|s390x|loongarch64'` if needed.

**Comment by h-vetinari** [comment]
Thanks for the explanation @uranusjr! That works fine for my purposes!
