### ISSUE TITLE
Disallow `*` version modifier for anything but `==` and `!=`

### ISSUE THREAD

**Issue by brettcannon** [pypa/packaging#566]
E.g. `<= 2.*` shouldn't be allowed. See https://discuss.python.org/t/how-to-pin-a-package-to-a-specific-major-version-or-lower/17077/ for the discussion.

Guessing at how to fix this, the grammar could disallow it or an explicit check somehow.

**Comment by encukou** [comment]
Where? In specifiers it should already be disallowed. ([code](https://github.com/pypa/packaging/blob/main/packaging/specifiers.py#L325), [tests](https://github.com/pypa/packaging/blob/main/tests/test_specifiers.py#L64))

**Comment by encukou** [comment]
Oh, this is a `LegacySpecifier`. Should be solved by https://github.com/pypa/packaging/pull/407.

```
>>> spec_set = packaging.specifiers.SpecifierSet('<=2.8.*')
>>> spec_set._specs
frozenset({<LegacySpecifier('<=2.8.*')>})
```

**Comment by pradyunsg** [comment]
Bundling into #530 then!
