### ISSUE TITLE
Move to an `src/` layout

### ISSUE THREAD

**Issue by pradyunsg** [pypa/packaging#568]
I got very confused a few minutes ago, because I had a local copy of packaging that was not able to parse `requests == 2.8.*` and that's obviously wrong. However, `pip list` only found the installed copy of packaging, and not the local copy of it.

**Comment by brettcannon** [comment]
I'm still not a massive fan, but I also realize I'm in the minority, so I won't stop you if you make the change.

**Comment by hauntsaninja** [comment]
It looks like this happened in https://github.com/pypa/packaging/pull/626

**Comment by pradyunsg** [comment]
Indeed!
