### ISSUE TITLE
Expose SpecifierSet._specs "publicly"

### ISSUE THREAD

**Issue by hauntsaninja** [pypa/packaging#573]
It's useful to be able to inspect the individual specifiers in a SpecifierSet, e.g., if you want to lint requirements or attempt to construct a concrete example that matches a SpecifierSet (rather than just filtering a preexisting set of versions).

**Comment by pradyunsg** [comment]
You can iterate through a specifier set.

<https://packaging.pypa.io/en/latest/specifiers.html#packaging.specifiers.SpecifierSet.__iter__>

**Comment by pradyunsg** [comment]
Given that the requested capability already exists, I'm gonna go ahead and close this.

**Comment by hauntsaninja** [comment]
Thanks and apologies — I missed that when skimming both codes and docs! In case this was not just a me thing, I opened #575, but feel free to close it if it makes the cheatsheet section unnecessarily verbose :-)
