### ISSUE TITLE
Bug in versions that combine digits and strings

### ISSUE THREAD

**Issue by OfriOuzan** [pypa/packaging#582]
Hi, 
I noticed a very strange pattern while comparing versions that combine digits and strings
```
>>> from packaging import version
>>> version.parse('1.0.1a') > version.parse('1.0.1a-2')
False
>>> version.parse('1.0.1a') > version.parse('1.0.1b-2')
False
>>> version.parse('1.0.1a') > version.parse('1.0.1c-2')
False
>>> version.parse('1.0.1a') > version.parse('1.0.1d-2')
True
>>> version.parse('1.0.1a') > version.parse('1.0.1e-2')
True

**Comment by uranusjr** [comment]
This gets us back to #321. `d` and `e` are not valid PEP 440 version components and therefore compare differently.

I’m wondering whether it’s a good idea to deprecate `parse` as a way to move forward deprecating legacy version and specifier. It’s generally not exactly those classes that confuse people, but the auto coersion that does.

**Comment by pradyunsg** [comment]
Closing this since #321 has happened and LegacyVersion has been removed.
