### ISSUE TITLE
Version 2022c is incorrectly parsed as a release canidate

### ISSUE THREAD

**Issue by shughes-uk** [pypa/packaging#585]
Easy one to replicate

```python
In [5]: version.parse("2022c")
Out[5]: <Version('2022rc0')>```

**Comment by abravalheri** [comment]
I think this equivalence is an intended behaviour described in PEP 440:

> The normalized form for release candidates was updated from ‘c’ to ‘rc’. This change was based on user feedback received when setuptools 8.0 started applying normalisation to the release metadata generated when preparing packages for publication on PyPI [[8]](https://peps.python.org/pep-0440/#id16).

**Comment by shughes-uk** [comment]
I guess my surprise here is that the version string ends up mutated to "2022rc0". Ideally it should be preserved as "2022c"

**Comment by abravalheri** [comment]
I understand the surprise, but it seems that `packaging` is just following the recommendations in PEP 440 by the book. There is a recommendation to normalise the version.

`c` gets normalised to `rc` and `rc` gets normalised to `rc0`. So when all the recommended normalisations are applied the final result is `2022rc0`

**Comment by shughes-uk** [comment]
Sigh. Thanks anyway. I think i'm mostly running into these issues because i'm parsing `conda` package versions which can conform to pep440 or not completely at randomly.

**Comment by pradyunsg** [comment]
https://github.com/conda/conda/blob/main/conda/models/version.py

It might be worth asking the conda folks if they provide their version parsing logic, in a manner that it can be reused.
