### ISSUE TITLE
Equality is missing in Requirement contrast to what is mentioned in the documentation

### ISSUE THREAD

**Issue by gmichaeljaison** [pypa/packaging#588]
The documentation mentions and shows example of simple equality operations. But it does not work with installed `packaging` package.

Expected:
```py
# You can do simple comparisons between requirement objects:
>>> Requirement("packaging") == Requirement("packaging")
True
>>> # You can also perform simple comparisons between sets of requirements:
>>> requirements1 = {Requirement("packaging"), Requirement("pip")}
>>> requirements2 = {Requirement("pip"), Requirement("packaging")}
>>> requirements1 == requirements2
```

Actual:
```py
>>> Requirement("packaging") == Requirement("packaging")
False
```

Version:
Python                   3.9
packaging             21.3

Documentation: https://packaging.pypa.io/en/latest/requirements.html

**Comment by pradyunsg** [comment]
What version of packaging are you using?

We have tests for this, and (I’m not a 100% sure about this next bit) that code sample should be getting tested via doctest as well.

https://github.com/pypa/packaging/blob/8c6a45e20857db912d397afb489832d9528a84c8/tests/test_requirements.py#L279

**Comment by uranusjr** [comment]
This was already implemented in #499 but not yet released. The documentation is not wrong either since the link is `latest` (which reflects the main branch); [documentation for the stable version](https://packaging.pypa.io/en/stable/requirements.html) does not contain the example.

**Comment by pradyunsg** [comment]
Indeed, cross linking to #569 and closing then. :)

**Comment by gmichaeljaison** [comment]
Thank you for the details. I believe instead of `latest` if it is labelled `dev` or `develop`, it might have been clearer.
Also google search always lists the `latest` documentation link somehow.
