### ISSUE TITLE
`version.parse` does not raise error for invalid version

### ISSUE THREAD

**Issue by fcnoronha** [pypa/packaging#594]
I'm currently running packaging 21.3 and even though [documentation shows](https://packaging.pypa.io/en/latest/version.html#packaging.version.parse) that both, `version.parse` and `version.Version`, should raise an error when the version is invalid, only the second one raises it, while the first one returns a `LegacyVersion` object.

**Comment by brettcannon** [comment]
It's because you're looking at the latest docs which match `main`, not the last release. Please see https://packaging.pypa.io/en/stable/version.html for the stable docs.
