### ISSUE TITLE
Squash to most restrictive range SpecifierSet

### ISSUE THREAD

**Issue by tdegeus** [pypa/packaging#598]
Consider:
```python
s = SpecifierSet("<1.0") & SpecifierSet("<2.0")
```
As `<1.0` is more restrictive than `<2.0` the latter can easily be forgotten. How can I achieve this? I.e. How do I squash a `SpecifierSet` to the most restrictive set?

**Comment by brettcannon** [comment]
The logic will still work out as `SpecifierSet("<1.0")` will overpower the `"<2.0"` specifier, so there isn't a logical reason to "squash" unless you are extremely performance-sensitive. But calculating the accurate subset is unfortunately not simple based on the complexity that specifiers can be, so I don't see us trying to add such a feature.

**Comment by pradyunsg** [comment]
> How can I achieve this?

You can't, as that has not been implemented today (AFAIK).

> I.e. How do I squash a `SpecifierSet` to the most restrictive set?

Well, you'd need significantly complex logic for computing that. As mentioned, that isn't implemented and there isn't much need to do so, unless you're noticing the lack of this as a bottleneck.

> there isn't a logical reason to "squash" unless you are extremely performance-sensitive.

And, even then, it's only an overhead *if* the SpecifierSet ordering doesn't short-circuit the comparision after the first comparision.

**Comment by tdegeus** [comment]
Thanks for the replies @brettcannon @pradyunsg . My worry was not the overhead in the comparison. Instead my application is aimed at merging several conda environment files. I did make something work ( https://github.com/tdegeus/conda_envfile ) but I thought it may have been simple in this library, and may have other use-cases as well.
