### ISSUE TITLE
Expose test dependencies outside of `noxfile.py`

### ISSUE THREAD

**Issue by brettcannon** [pypa/packaging#601]
Right now the only way to run the tests outside of running `nox -s tests` is to manually install what's hard-coded there:

https://github.com/pypa/packaging/blob/44efc1f464b5a5eb467b8d851d1734feb7560b27/noxfile.py#L31

This is problematic if you want to set up your editor for running your tests before you take the next step with nox to run the tests on all installed versions of Python.

We could create a `test` optional dependency so that we can change:

https://github.com/pypa/packaging/blob/44efc1f464b5a5eb467b8d851d1734feb7560b27/noxfile.py#L32

to be `.[test]`. And I'm specifically suggesting `test` over `tests` because that's [what the core metadata chose as a name](https://packaging.python.org/en/latest/specifications/core-metadata/#provides-extra-multiple-use).

We could also do this for documentation with a `doc` extra.

**Comment by pradyunsg** [comment]
I won't mind mirroring pip -- and having a docs/requirements.txt and tests/requirements.txt. :)

**Comment by brettcannon** [comment]
That also works for me if that's the route you want to go.
