### ISSUE TITLE
tags._generic_abi should use only the first part of the SOABI

### ISSUE THREAD

**Issue by mattip** [pypa/packaging#606]
In [_generic_abi()](https://github.com/pypa/packaging/blob/0031046f7fad649580bc3127d1cef9157da0dd79/packaging/tags.py#L228) (which is used on non-CPython), the abi tag is equivalent to the SOABI sysconfig value. But this is `"cpython-38-x86_64-linux-gnu"` on CPython. The equivalent code path for CPython goes to [_cpython_abis()](https://github.com/pypa/packaging/blob/0031046f7fad649580bc3127d1cef9157da0dd79/packaging/tags.py#L135) which does not use SOABI at all. Currently, PyPy must keep its SOABI to `"pypy38-pp73"` in order to allow pip to function. The EXTSUFFIX is `"".pypy38-pp73-x86_64-linux-gnu.so"`. This was fixed for wheel in pypa/wheel#372 and should be fixed here as well.

It seems CMake uses the SOABI, so building projects with PyPy there requires work-arounds. Here is the PyPy issue https://foss.heptapod.net/pypy/pypy/-/issues/3816

**Comment by mattip** [comment]
thinking about how to test this: the same result should be produced by `_cpython_abis()` and `_generic_abis()`

**Comment by brettcannon** [comment]
Some other details can be found in https://github.com/pypa/packaging/issues/606 which was failed simultaneously.

**Comment by brettcannon** [comment]
Welcome to the historical baggage that is wheel tag generation. 😉 Not saying we can't consider changing it, but this wasn't by design as much as organic growth when I collected all the various implementations together and this bifurcation of logic already existed.
