### ISSUE TITLE
22.0: The new requirement parser doesn't handle unnormalized specifiers

### ISSUE THREAD

**Issue by frostming** [pypa/packaging#629]
```python
from packaging.specifiers import SpecifierSet
from packaging.requirements import Requirement

s = SpecifierSet('>=1.0-alpha')  # success
"1.0a0" in s  # True

r = Requirement('foo>=1.0-alpha')  # Error
```

Ideally, we should make them consistent.

**Comment by hroncok** [comment]
For the record, `Requirement('foo>=1.0-alpha')` worked with packaging 21 (I've double-checked since it wasn't mentioned in the issue explicitly).

**Comment by pradyunsg** [comment]
Did it parse as a LegacySpecifier?

If not, this might be a discrepancy between the logic in the new parser vs Specifier. Thinking a bit more, it might make sense to tweak the parser to try and directly match using the Specifier regex itself.

**Comment by pradyunsg** [comment]
It's a discrepency.

**Comment by pradyunsg** [comment]
```
packaging.requirements.InvalidRequirement: Expected end or semicolon (after version specifier)
     foo >= 1.0-alpha 
         ~~~~~~~~^
```

The error message gives a hint of what's happening: `1.0-a` is getting parsed as the version here.

**Comment by henryiii** [comment]
I expect this is what is breaking build’s test suite with 22.0. Probably should verify the dev version fixes build’s tests. I’m on vacation through tomorrow so can’t check till the weekend. Anyone else from @pypa/build?
