### ISSUE TITLE
Finding the best tag from a list

### ISSUE THREAD

**Issue by rth** [pypa/packaging#636]
There are cases where there are multiple compatible tags and the question is how to select the best tag.
For instance in https://github.com/pyodide/micropip/issues/32  @mentalisttraceur reported a use case where,
- compose-1.4.8-py38-none-any.whl 
- compose-1.4.8-py35-none-any.whl 
- compose-1.4.8-py2.py30-none-any.whl

exist, and builds for later Python versions use more latest Python features and so should be preferred. As far as I understand no API for this exists in `packaging`, although there are related discussions in https://github.com/pypa/packaging/issues/602.

I was wondering if adding the comparison operator in `Tag` e.g.
```py
from packaging.tags import Tag
assert (Tag("py38", "none", "any") > Tag("py35", "none", "any")) is True
```
would be one way of solving this issue with the current API. With the idea being that the latest Python versions and more specialized (compiled) builds are to be preferred. 

Then one could just sort the available tags before checking if they are compatible to pick the best tag. WDYT? I'm not sure how this is currently done in other package managers.

**Comment by pradyunsg** [comment]
This is provided by sys_tags returned an ordered list, with the initial entries in the list being preferred over later entries.

**Comment by pradyunsg** [comment]
https://packaging.pypa.io/en/stable/tags.html#packaging.tags.sys_tags

I have to fix a bug in Furo.

**Comment by rth** [comment]
Indeed, that works, thanks! I should have read the docs better )
