### ISSUE TITLE
InvalidSpecifier with comparison operators for versions with local version label

### ISSUE THREAD

**Issue by pradyunsg** [pypa/packaging#637]
```sh-session
❯ python -c 'import packaging; print(packaging.__version__); import packaging.specifiers as s; print(vars(s.SpecifierSet("==0.1.dev126+gaeebca2")))'
21.3
{'_specs': frozenset({<Specifier('==0.1.dev126+gaeebca2')>}), '_prereleases': None}
❯ python -c 'import packaging; print(packaging.__version__); import packaging.specifiers as s; print(vars(s.SpecifierSet("==0.1.dev126+gaeebca2")))'
22.0
{'_specs': frozenset({<Specifier('==0.1.dev126+gaeebca2')>}), '_prereleases': None}
❯ python -c 'import packaging; print(packaging.__version__); import packaging.specifiers as s; print(vars(s.SpecifierSet(">=0.1.dev126+gaeebca2")))'
21.3
{'_specs': frozenset({<LegacySpecifier('>=0.1.dev126+gaeebca2')>}), '_prereleases': None}
❯ python -c 'import packaging; print(packaging.__version__); import packaging.specifiers as s; print(vars(s.SpecifierSet(">=0.1.dev126+gaeebca2")))'
22.0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/venv/lib/python3.10/site-packages/packaging/specifiers.py", line 700, in __init__
    parsed.add(Specifier(specifier))
  File "/tmp/venv/lib/python3.10/site-packages/packaging/specifiers.py", line 234, in __init__
    raise InvalidSpecifier(f"Invalid specifier: '{spec}'")
packaging.specifiers.InvalidSpecifier: Invalid specifier: '>=0.1.dev126+gaeebca2'
```

It's not clear from reading PEP 508 / PEP 440 how these cases should be handled. Equality is likely reasonable to have, although I've not actually tested the _membership_ of these specifiers.

**Comment by pradyunsg** [comment]
Thoughts and quotes from PEPs welcome. :)

**Comment by jgkatz** [comment]
Shouldn't it be valid based on: 

https://peps.python.org/pep-0440/#local-version-identifiers

Seems like + symbol is being rejected no matter what.

**Comment by konstin** [comment]
From my read on PEP 440 `==` is valid with a local version, but `>=`/`>` must be rejected with a local version (as it is implemented in 22.0):

[Version matching](https://peps.python.org/pep-0440/#version-matching)

> If the specified version identifier is a public version identifier (no local version label), then the local version label of any candidate versions MUST be ignored when matching versions.
> 
> If the specified version identifier is a local version identifier, then the local version labels of candidate versions MUST be considered when matching versions, with the public version identifier being matched as described above, and the local version label being checked for equivalence using a strict string equality comparison.

[Inclusive ordered comparison](https://peps.python.org/pep-0440/#inclusive-ordered-comparison)

> Local version identifiers are NOT permitted in this version specifier.

**Comment by pradyunsg** [comment]
> Seems like + symbol is being rejected no matter what.

It's being rejected in operators other than `==`.

---

Ah, Thanks @konstin! Sounds like the current behaviour is the right behaviour then. :)

**Comment by pradyunsg** [comment]
Another relevant quote:

> Except where specifically noted below, local version identifiers MUST NOT be permitted in version specifiers, and local version labels MUST be ignored entirely when checking if candidate versions match a given version specifier.
