### ISSUE TITLE
How to handle invalid version in 22.0?

### ISSUE THREAD

**Issue by Hoohaha** [pypa/packaging#640]
Hi,

LegacyVersion class has been dropped in 22.0. But how to force parse invalid version number?

**Comment by pradyunsg** [comment]
You can't, with packaging going forward. This package is meant for Python packaging tooling, which primarily deals with well-formed versions. Taking improper versions was a major source of confusion.

We've suggested that users who wish to use that functionality either stick to an older version of packaging or take the code and, publish it as a separate package (https://github.com/pypa/packaging/issues/502#issuecomment-1024866175) which can evolve on its own. I'm not aware of anyone actually doing that but it might be worth checking. :)
