### ISSUE TITLE
Version parsing error in packaging 22.0

### ISSUE THREAD

**Issue by WillChen789** [pypa/packaging#651]
Hello, I recently observed some unexpected behavior with packaging 22.0 where `version.parse` will throw an exception when multiple comma-separated version numbers are provided to the function.

To repro:
````
from packaging.version import parse
print(parse('0.10.1,<0.11'))
````
Executing this with packaging 21.3 will return the expected output:
```
0.10.1,<0.11
```
Whereas executing this with packaging 22.0 will throw an InvalidVersion exception:
```
InvalidVersion: Invalid version: '0.10.1,
```

Was this an intended change? For context, please see `transformers` for a live example where this is relevant: https://github.com/huggingface/transformers/blob/main/src/transformers/dependency_versions_table.py

Thank you for your attention regarding this issue.

**Comment by uranusjr** [comment]
The string you provide is indeed invalid, not raising an exception is a but. I’d say this is a good bug fix.

**Comment by pradyunsg** [comment]
This is intentional, and explicitly rejecting a string that is not a version (in `packaging.version.parse` is indeed an intended change).

**Comment by pradyunsg** [comment]
See #631 for the details.

**Comment by pradyunsg** [comment]
See #321 and #530 for the details.
