### ISSUE TITLE
Spaces in platform names are problematic

### ISSUE THREAD

**Issue by tucked** [pypa/packaging#652]
On some platforms, `sysconfig.get_platform()` returns a value with a space in it (e.g. `isilon onefs`).
This causes problems for wheel building/handling.

First, there is an issue trying to build a platform-specific wheel:
``` console
# venv/bin/pip install -I --no-cache pyyaml
Collecting pyyaml
  Downloading PyYAML-6.0.tar.gz (124 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.0/125.0 KB 13.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pyyaml
  Building wheel for pyyaml (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pyyaml (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [101 lines of output]
...
      wheel.cli.WheelError: Bad wheel filename 'PyYAML-6.0-cp38-cp38-isilon onefs_9_5_0_0_amd64.whl'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyyaml
```
I created https://github.com/pypa/wheel/pull/491 to address this.

Even with that patch in place, though, `pip` is unable to install the built wheel because `packaging` does not recognize that the platform name has had its spaces replaced with underscores:
``` console
# python3 -m pip install dist/PyYAML-6.0-cp38-cp38-isilon_onefs_9_5_0_0_amd64.whl
...
ERROR: PyYAML-6.0-cp38-cp38-isilon_onefs_9_5_0_0_amd64.whl is not a supported wheel on this platform.
```

**Comment by brettcannon** [comment]
Can you point where in the `packaging` code base is the falling over?

And the "fun" part of this is https://peps.python.org/pep-0425/#platform-tag doesn't specify what to do with spaces (and actually, "space" is not mentioned once in the PEP). `_` makes the most sense thanks to how it escapes everything else, but it's technically undefined.

**Comment by tucked** [comment]
> Can you point where in the `packaging` code base is the falling over?

If we use `PyYAML-6.0-cp38-cp38-isilon_onefs_9_5_0_0_amd64.whl`[^1], for example, we can work backwards from [the error](https://github.com/pypa/pip/blob/a057c9bc99ad7eab2e3b1539e79eee7d9a923f4f/src/pip/_internal/resolution/legacy/resolver.py#L233-L237).
- First, [`pip` instantiates a `Wheel` object](https://github.com/pypa/pip/blob/a057c9bc99ad7eab2e3b1539e79eee7d9a923f4f/src/pip/_internal/resolution/legacy/resolver.py#L230) which [parses the file name](https://github.com/pypa/pip/blob/a057c9bc99ad7eab2e3b1539e79eee7d9a923f4f/src/pip/_internal/models/wheel.py#L15-L26) and [gets `'isilon_onefs'` for the platform](https://github.com/pypa/pip/blob/a057c9bc99ad7eab2e3b1539e79eee7d9a923f4f/src/pip/_internal/models/wheel.py#L37-L42).
  - Interestingly, it grabs spaces in the platform name.
- Then, [it uses `packaging` (vendored)](https://github.com/pypa/pip/blob/a057c9bc99ad7eab2e3b1539e79eee7d9a923f4f/src/pip/_internal/utils/compatibility_tags.py#L143-L147) to [check if the platform tag is supported by the current platform](https://github.com/pypa/pip/blob/a057c9bc99ad7eab2e3b1539e79eee7d9a923f4f/src/pip/_internal/resolution/legacy/resolver.py#L231-L232).
  - `cpython_tags` calls `platform_tags`: https://github.com/pypa/packaging/blob/206797003d9bf9c04d3db17c564d13eae9e4e54a/src/packaging/tags.py#L211
  - `platform_tags` calls `_generic_platforms` (because `platform.system()` would be `'Isilon OneFS'`): https://github.com/pypa/packaging/blob/206797003d9bf9c04d3db17c564d13eae9e4e54a/src/packaging/tags.py#L496
  - `_generic_platforms` normalizes the platform name: https://github.com/pypa/packaging/blob/206797003d9bf9c04d3db17c564d13eae9e4e54a/src/packaging/tags.py#L483-L484
  - However, it does NOT normalize spaces: https://github.com/pypa/packaging/blob/206797003d9bf9c04d3db17c564d13eae9e4e54a/src/packaging/tags.py#L122-L123
- Ultimately `pip` decides that the wheel is not supported because `'isilon_onefs' != 'isilon onefs'`.

AFAICT, the only alternative would be to have `pip` turn underscores to spaces, which seems... problematic.
The only known workaround is to set `UNAME_s=isilon_onefs` during `pip install` to manually normalize the platform name.

[^1]: Remember that `PyYAML-6.0-cp38-cp38-isilon_onefs_9_5_0_0_amd64.whl` can only be built with https://github.com/pypa/wheel/pull/491 (or by setting `UNAME_s=isilon_onefs` during the build).

**Comment by brettcannon** [comment]
OK, that makes sense.

In https://github.com/pypa/packaging/pull/620#issuecomment-1371550255 , @tucked noticed we now have a test that's explicitly checking an example with spaces, but I think that's just for parsing purposes and not normalization. But to double-check, @mattip , do you see any reason not to do this since I think you may have written the test in question?

@pradyunsg you okay with this change?

**Comment by pradyunsg** [comment]
Yup! Do we want to update the spec language to cover spaces -> underscore?

**Comment by mattip** [comment]
The test was only meant to check round-trip behavior. It should not use spaces.

**Comment by brettcannon** [comment]
> Yup! Do we want to update the spec language to cover spaces -> underscore?

I think so, but I think it's going to require bringing PEP 425 over to packaging.python.org first.

**Comment by tucked** [comment]
Is this not covered [in PEP 427](https://peps.python.org/pep-0427/#escaping-and-unicode):
> Each component of the filename is escaped by replacing runs of non-alphanumeric characters with an underscore `_`?
> ``` python
> re.sub("[^\w\d.]+", "_", distribution, re.UNICODE)
> ```

**Comment by brettcannon** [comment]
> Is this not covered [in PEP 427](https://peps.python.org/pep-0427/#escaping-and-unicode)

Technically it doesn't matter because that's not the spec anymore (as the top of the PEP says). The spec is now https://packaging.python.org/en/latest/specifications/binary-distribution-format/#escaping-and-unicode and it actually doesn't mention anything about spaces, just that the wheel tags need to be valid. And the wheel tag spec at https://packaging.python.org/en/latest/specifications/platform-compatibility-tags/ redirects to PEP 425 which also lacks an opinion.

**Comment by brettcannon** [comment]
I opened https://github.com/pypa/packaging.python.org/pull/1206 to move PEP 425 over to packaging.python.org.
