### ISSUE TITLE
`print()` calls in `test_tags`

### ISSUE THREAD

**Issue by brettcannon** [pypa/packaging#667]
https://github.com/pypa/packaging/blob/068a0b5975a95a5cc30262599ca29bb6ceabe4af/tests/test_tags.py#L237
https://github.com/pypa/packaging/blob/068a0b5975a95a5cc30262599ca29bb6ceabe4af/tests/test_tags.py#L245
https://github.com/pypa/packaging/blob/068a0b5975a95a5cc30262599ca29bb6ceabe4af/tests/test_tags.py#L255
https://github.com/pypa/packaging/blob/068a0b5975a95a5cc30262599ca29bb6ceabe4af/tests/test_tags.py#L273

**Comment by pradyunsg** [comment]
Is this problematic? What's actionable here?

pytest captures their output and shows it in failure, which can be useful for diagnostics.

**Comment by brettcannon** [comment]
> Is this problematic?

No, just annoying when staring at the output to spot any failures and this wall of tags shows up.


> What's actionable here?

Delete the `print()` calls.



> pytest captures their output and shows it in failure messages, which can be useful for diagnostics.

But if you run the tests w/ `-s`/`--capture=no` then it gets interspersed with the test results (as is required if you want to run the tests under WASI).

**Comment by pradyunsg** [comment]
Oh, wow. Why is that required under WASI?

**Comment by brettcannon** [comment]
> Oh, wow. Why is that required under WASI?

https://github.com/pytest-dev/pytest/issues/10670 for the details, but basically WASI doesn't support `os.dup()` and pytest uses it for capturing output.

**Comment by Zac-HD** [comment]
(alternatively, if we can come up with an `os.dup()`-free way to do output capture, I'd be happy to get that into Pytest for use on wasm even if it's pretty restricted)
