### ISSUE TITLE
Is it possible to add `platform_architecture` to the markers?

### ISSUE THREAD

**Issue by kadiremir** [pypa/packaging#672]
To learn the platform of **Python.exe** which is running, is it possible to add 

`"platform_architecture": platform.arcitecture()[0],`

to the markers.py?

Because the other available markers such as `sys_platform` and `platform_machine` are returning the platform of the machine, not Python application.

**Comment by Jackenmen** [comment]
Markers in this package are implemented based on the specification in PEP 508 (https://peps.python.org/pep-0508/#environment-markers). If you want another marker to be added, that PEP would need to be changed (or perhaps another made). Such ideas can be brought up on discuss.python.org in Packaging category.
