### ISSUE TITLE
compare pre-release version

### ISSUE THREAD

**Issue by quinzhi** [pypa/packaging#677]
Hi!
I know that the pre-release version is the lower version, but when it comes to a higher major, minor or patch version and the pre-release version is not 'alpha' or 'beta', i think the the version with higher major, minor or patch is higher? 
```python
>>> version.parse('1.0.0') < version.parse('1.2.0-alpha')
True
>>> version.parse('1.0.0') < version.parse('1.2.0-beta')
True
>>> version.parse('1.0.0') < version.parse('1.2.0-final')
False
```

**Comment by Jackenmen** [comment]
`version.parse("1.2.0-final")` raises an exception and `version.parse("1.0.0") < version.parse("1.2.0")` evaluates to `True` so I'm not sure what issue you're running into.

Currently, PEP 440 is the source of truth for the information about the relative ordering of versions and this package just implements the logic described there. The examples here may make it most obvious to you what kind of order is expected:
https://peps.python.org/pep-0440/#summary-of-permitted-suffixes-and-relative-ordering

**Comment by quinzhi** [comment]
@Jackenmen Thanks！

**Comment by quinzhi** [comment]
> `version.parse("1.2.0-final")` raises an exception and `version.parse("1.0.0") < version.parse("1.2.0")` evaluates to `True` so I'm not sure what issue you're running into.
> 
> Currently, PEP 440 is the source of truth for the information about the relative ordering of versions and this package just implements the logic described there. The examples here may make it most obvious to you what kind of order is expected: https://peps.python.org/pep-0440/#summary-of-permitted-suffixes-and-relative-ordering

How can i catch that exception so that i can deal with that kind of versoin myself? Can i use ```_regex```?
```python
>>> hasattr(version.parse('1.2.0-final'), "_regex")
False
>>> hasattr(version.parse('1.2.0'), "_regex")
True

```

**Comment by pradyunsg** [comment]
You can use packaging.version.Version instead of the alternative.

**Comment by quinzhi** [comment]
@pradyunsg Thanks！
