### ISSUE TITLE
Does `version.parse` still have a purpose?

### ISSUE THREAD

**Issue by MrMino** [pypa/packaging#679]
Currently `parse` boils down to the following one-liner:

```
Version(version)
```

Is there still any future usecase for it, or is it just a leftover from `LegacyVersion` times that one can now avoid, and use `Version` directly instead? Are there any plans to deprecate it?

Docs do not specify whether one is preferred over another, but right now it seems like `parse` is just redundant function call overhead.

I understand the need to preserve `parse` in its current form for API stability, but it would be nice to indicate which one is future-proof / whether one can call `Version(...)` directly and not have to worry about any additions to the spec being implemented outside of it.

**Comment by MrMino** [comment]
FWIW using `Version` directly also minimizes number of imports when using type hints :wink:.

**Comment by pradyunsg** [comment]
Calling Version directly is totally OK. I don't expect we'd be enforcing that in any way.

**Comment by pradyunsg** [comment]
> Are there any plans to deprecate it?

No, because it has ~0 cost and consumers needing to change their calls is unnecessary churn IMO.

**Comment by MrMino** [comment]
That's fine, but the docs are a bit ambiguous. Grice maxims come into play here and if the docs give me two different ways of doing something, I automatically assume that they are not equivalent. This is probably the case for most humans :).

Would you be open to adding this to the `parse` docs?

```
This is the same as calling `Version(...)` directly.
```

**Comment by pradyunsg** [comment]
#597 would likely involve covering this, so a PR making any level of progress toward that would be welcome!
