### ISSUE TITLE
Set up permissions to github workflows

### ISSUE THREAD

**Issue by joycebrum** [pypa/packaging#680]
I have suggested a PR to setuptools repo to harden permissions to the github workflows https://github.com/pypa/setuptools/pull/3833, if that's ok, I also would like to do the same to the packaging repo in order to increase supply-chain security by limiting the impact of an eventual compromised workflow.

Let me know if a PR is also welcome in this repo and I'll submit it ASAP.

**Comment by pradyunsg** [comment]
Thanks for flagging! I've set the default permissions in the settings for the repo to read, instead of needing to modify the workflows directly.

If someone is able to compromise/modify the settings of this repo, we're already compromised at that point so I reckon this is good enough! :)
