### ISSUE TITLE
Regression when parsing `pytz (>=2011k)` after 21.3 to 22.0 upgrade

### ISSUE THREAD

**Issue by alexey-medvedchikov** [pypa/packaging#681]
Hi,

Thank you for all your hard work!

At some point we upgraded packaging from v21.3 to v22.0 and found a regression.

v21.3 works fine:

```plain
# pip3.7 install packaging==21.3
...
# echo "pytz (>=2011k)" | python3.7 -c "import packaging; from packaging.requirements import Requirement; print(vars(Requirement(input())))"
{'name': 'pytz', 'url': None, 'extras': set(), 'specifier': <SpecifierSet('>=2011k')>, 'marker': None}
```

v23.0 and v22.0 are broken (last version that works is v21.3):

```plain
# pip3.7 install packaging==23.0
...

# echo "pytz (>=2011k)" | python3.7 -c "import packaging; from packaging.requirements import Requirement; print(vars(Requirement(input())))"
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/packaging/requirements.py", line 35, in __init__
    parsed = parse_requirement(requirement_string)
  File "/usr/local/lib/python3.7/site-packages/packaging/_parser.py", line 64, in parse_requirement
    return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
  File "/usr/local/lib/python3.7/site-packages/packaging/_parser.py", line 82, in _parse_requirement
    url, specifier, marker = _parse_requirement_details(tokenizer)
  File "/usr/local/lib/python3.7/site-packages/packaging/_parser.py", line 120, in _parse_requirement_details
    specifier = _parse_specifier(tokenizer)
  File "/usr/local/lib/python3.7/site-packages/packaging/_parser.py", line 209, in _parse_specifier
    tokenizer.consume("WS")
  File "/usr/local/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.7/site-packages/packaging/_tokenizer.py", line 185, in enclosing_tokens
    span_start=open_position,
  File "/usr/local/lib/python3.7/site-packages/packaging/_tokenizer.py", line 166, in raise_syntax_error
    span=span,
packaging._tokenizer.ParserSyntaxError: Expected closing RIGHT_PARENTHESIS
    pytz (>=2011k)
         ~~~~~~~^
```

Test to reproduce the issue:

```python
def test_specifier_ends_with_letter(self) -> None:
    # GIVEN
    to_parse = "name (>=2011k)"

    # WHEN
    req = Requirement(to_parse)

    # THEN
    assert req.name == "name"
    assert req.specifier == SpecifierSet('>=2011k')
```

Output from the test on current main:

```
self = <[AttributeError("'Requirement' object has no attribute 'name'") raised in repr()] Requirement object at 0x7fc3a1427040>
requirement_string = 'name (>=2011k)'

    def __init__(self, requirement_string: str) -> None:
        try:
            parsed = parse_requirement(requirement_string)
        except ParserSyntaxError as e:
>           raise InvalidRequirement(str(e)) from e
E           packaging.requirements.InvalidRequirement: Expected closing RIGHT_PARENTHESIS
E               name (>=2011k)
E                    ~~~~~~~^
```

**Comment by brettcannon** [comment]
This is expected as `2100k` is not a valid version number (see https://packaging.python.org/en/latest/specifications/version-specifiers/ for the spec). Starting in `packaging` 22 we stopped being permissive about this, hence the change in semantics (we raised a warning to try and let users know ahead of time that this change was coming).

**Comment by pradyunsg** [comment]
See https://github.com/pypa/packaging/issues/530

**Comment by alexey-medvedchikov** [comment]
Thanks @brettcannon for the info. This is sad. :disappointed:

**Comment by SouhaibUniv** [comment]
C:\Windows\system32>pip install google.colab

Collecting google.colab
  Using cached google-colab-1.0.0.tar.gz (72 kB)
  Preparing metadata (setup.py) ... done
Collecting google-auth~=1.4.0 (from google.colab)
  Using cached google_auth-1.4.2-py2.py3-none-any.whl (64 kB)
Collecting ipykernel~=4.6.0 (from google.colab)
  Using cached ipykernel-4.6.1-py3-none-any.whl (104 kB)
Collecting ipython~=5.5.0 (from google.colab)
  Using cached ipython-5.5.0-py3-none-any.whl (758 kB)
Collecting notebook~=5.2.0 (from google.colab)
  Using cached notebook-5.2.2-py2.py3-none-any.whl (8.0 MB)
Collecting six~=1.12.0 (from google.colab)
  Using cached six-1.12.0-py2.py3-none-any.whl (10 kB)
Collecting pandas~=0.24.0 (from google.colab)
  Using cached pandas-0.24.2.tar.gz (11.8 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      C:\Program Files\Python310\lib\site-packages\setuptools\__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!

              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************

      !!
        dist.fetch_build_eggs(dist.setup_requires)
      error in pandas setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after version specifier)
          pytz >= 2011k
               ~~~~~~~^
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
