### ISSUE TITLE
CHANGELOG.rst is not included in the source tarball, making the documentation unbuildable

### ISSUE THREAD

**Issue by doko42** [pypa/packaging#688]
$ cat docs/changelog.rst
.. include:: ../CHANGELOG.rst

however it's not included in the source tarball

**Comment by brettcannon** [comment]
Interested in opening a PR to update:

https://github.com/pypa/packaging/blob/55584fb5ca327ba38b74ca5c668125caaebd9a5d/pyproject.toml#L38

?
