### ISSUE TITLE
Create a Github Security Policy File

### ISSUE THREAD

**Issue by joycebrum** [pypa/packaging#694]
Hi, I'd like to know if you might have interest on creating a Github Security Policy file for pypa/packaging. The project already has a very well defined security policy so the file would only allow users to get this information through github standard ways.

It will be shown in the [Security Dashboard](https://github.com/joycebrum/packaging/security) and in the about section of the project:

<img width="339" alt="image" src="https://github.com/pypa/packaging/assets/22223372/fe13c2aa-b24a-4517-8d70-568766669dc4">

So it will make it easier for users to find out how to report security issues. Optionally we can also edit the CONTRIBUTING file to mention the security policy just to avoid repetition ([example](https://github.com/joycebrum/packaging/blob/main/CONTRIBUTING.rst)).

I've made the changes in this fork https://github.com/joycebrum/packaging if you want to take a closer look. Let me know if a PR is welcome and I'll submit it ASAP.

Thanks!

**Comment by pradyunsg** [comment]
Please feel welcome to file a PR!
