### ISSUE TITLE
How to do `is_subset`  validation with `SpecifierSet`?

### ISSUE THREAD

**Issue by drunkwcodes** [pypa/packaging#707]
I'm rewriting `pdm` for Mojo language's use. Thank you for making this gorgeous package that even works with another language.

I use this package more heavily than `pdm`, which rewrite its own custom [SpecifierSet - PySpecSet](https://github.com/pdm-project/pdm/blob/main/src/pdm/models/specifiers.py#L85) for Python version specifiers.

It uses upper, lower bounds and excluding versions to do `__and__` operation and **is_subset** [check](https://github.com/pdm-project/pdm/blob/main/src/pdm/models/repositories.py#L162).

I'm finding more elegant way to achieve the same goal.
How to use `SpecifierSet` to do `is_subset` check, checking package candidate's require_python is a subset of requirement's to assert the package is compatible?

**Comment by brettcannon** [comment]
`SpecifierSet` is an iterable, so you can do something like:
```python
def is_subset(superset, subset):
    return all(spec in superset for spec in subset)
```

**Comment by drunkwcodes** [comment]
@brettcannon Thank you. It's definitely elegant!

**Comment by drunkwcodes** [comment]
I found that `spec in superset` is not possible but `version in superset` is.
So the final implementation is like this:

```python
from packaging.version import Version
from semver import Version as SemVer

def is_subset(superset, subset):
    # Rough impl.
    versions = []
    for spec in subset:
        vstr = str(spec).split(spec.operator)[-1]
        try:
            version = SemVer.parse(vstr)
        except ValueError:  # semantic version is strict to have patch number.
            vstr += ".0"
            version = SemVer.parse(vstr)

        if spec.operator == ">":
            version = Version(str(version.bump_patch()))

        elif spec.operator == "<":
            version = SemVer(major=version.major, minor=version.minor - 1, patch=version.patch)
            version = Version(str(version))
        
        versions.append(version)
    return all( version in superset for version in versions)
```

It will be buggy due to the rough version manipulation. If `spec in specset` can be done that would be great!
