### ISSUE TITLE
23.2 changelog mentions `utils.validate_name()` instead of `utils.normalize_name()`

### ISSUE THREAD

**Issue by dnicolodi** [pypa/packaging#730]
The changelog says:

> Introduce the validate keyword parameter to utils.validate_name() ([#570](https://github.com/pypa/packaging/issues/570))

But it should be

> Introduce the validate keyword parameter to utils.normalize_name() ([#570](https://github.com/pypa/packaging/issues/570))

**Comment by brettcannon** [comment]
@dnicolodi were you interested in submitting a PR?

**Comment by dimbleby** [comment]
it should have been `canonicalize_name()` anyway!
