### ISSUE TITLE
Publish `packaging` with a trusted publisher?

### ISSUE THREAD

**Issue by woodruffw** [pypa/packaging#737]
I looked for a previous issue; please close this with extreme prejudice if I missed it 🙂 

## Background

PyPI has an authentication mechanism called "trusted publishing," whereby a PyPI project that uses GitHub (and, in the future, other hosts) can configure a trust relationship between the PyPI project and its source repository. This relationship is verified through OpenID Connect, allowing a trusted workflow on GitHub Actions to mint ephemeral PyPI API tokens to publish without manual configuration or scoping.

Trusted publishing comes with several security and usability benefits: the API tokens it creates are self-expiring and tightly scoped, and eliminate confusion around user and project associations on PyPI (since the trusted publisher is tied directly to the project, rather than a user).

Some more details here from PyPI's docs: https://docs.pypi.org/trusted-publishers/

## Proposal

I propose adding a publishing workflow to `packaging`'s CI, one that will use the trusted publishing feature to automatically retrieve an API token.

This will require some coordination with a PyPI owner of `packaging`, specifically to perform a one-time trusted configuration step:

```
Repository Owner: pypa
Repository Name: packaging
Workflow Name: release.yml
Environment Name: release
```

(Where `release.yml` and `release` could be `publish.yml` or similar instead; this is ultimately your preference 🙂)

For some prior art (and related recommendations), https://github.com/certifi/python-certifi/pull/231 shows how the same process went for `certifi`.

**Comment by pradyunsg** [comment]
I agree that we should do this. Consolidating this into https://github.com/pypa/packaging/issues/339 though, since there's a broader "this whole thing should be automated" piece here.
