### ISSUE TITLE
Legacy versions aren't in SpecifierSets if the specifier is PEP 440-compatible

### ISSUE THREAD

**Issue by jimporter** [pypa/packaging#74]
Suppose you have a version and a specifier, both as strings. The version is _not_ PEP 440-compatible, but the specifier _is_. Creating version/specifier objects for each results in the version never meeting specifier:

``` python
>>> from packaging import version, specifiers
>>> v = version.parse('1.2.3.goofy')
>>> v
<LegacyVersion('1.2.3.goofy')>
>>> spec = specifiers.SpecifierSet('>=1.2')
>>> spec
<SpecifierSet('>=1.2')>
>>> v in spec
False
```

Presumably, this is because `LegacyVersion`s "will always sort as less than a `Version` instance."

While some people can just switch to PEP 440-compatible versions, not everyone can. In particular, I'm using this to parse _non_-Python versions for some tools. I could write my own code for this, but since I already need the `packaging` package for other stuff, I figured I should just use what already exists.

For my particular issue, I can think of the following solutions:
1. Write a new version parsing package that doesn't try to enforce PEP 440.
2. Add a `legacy=False` argument to `SpecifierSet` that will force all the specifiers it creates to be `LegacySpecifier`s. That way, if you know you need to handle legacy versions, you can enable it.
3. Figure out a way to make `Version`s and `LegacyVersion`s more compatible so that `LegacyVersion`s don't always count as older.

Thoughts?

**Comment by dstufft** [comment]
I think this seems like a reasonable idea, although I think I would call it ``LegacySpecifierSet`` because I think we'd also want to disable the specialized pre-release handling (since that matches the legacy behavior better).

**Comment by di** [comment]
Closing this as we've deprecated `LegacyVersion`/`LegacySpecifier` entirely in #342.
