### ISSUE TITLE
From an installed python-package, how to get the list of installed modules?

### ISSUE THREAD

**Issue by woutervh** [pypa/packaging#745]
packaging allows for querying the metadata of an installed python-package.

Going through the code and the documentation, I don't see a way to get the python-module(s) that are installed when you install a package.

Is this not supported? 
Or is there an implicit assumption that the installed module is the canonicalized package-name?

**Comment by brettcannon** [comment]
> packaging allows for querying the metadata of an installed python-package.

What API are you referring to for this? We actually don't do any I/O and that would be required in this instance.



> Going through the code and the documentation, I don't see a way to get the python-module(s) that are installed when you install a package.
> 
> Is this not supported?

Nope, it's not something we provide and there isn't a direct way to know this as Python's import system is flexible enough that you can't rely on file names to necessarily map to module names.

**Comment by woutervh** [comment]
> What API are you referring to for this?

 in setup.py or equivalent, you specify regular metadata, but also the list of packages:
```
setuptools.setup(
    name="foo",
    version=0.1,
    ...
    author="...",
    author_email="...",
    license="MIT", 
    packages=setuptools.find_packages("src"),
    ...
    )
```

 ```
 import importlib.metadata

info = importlib.metadata.metadata(foo)
author = info.get("author", "unknown")
version = info.get("version", "unknown")
packages = ??    <--  how to get this
 ```
 
 
 > as Python's import system is flexible enough that you can't rely on file names to necessarily map to module names.

In that case you still specify something in the packages-attribute in setup.py?
 

 My use-case for asking: I want to detect if pip-installing a new package will delete or shadow code of another package:
  ```
 > python3 -m venv demo && cd demo
 > bin/pip install django-dotenv     # installs toplevel module "dotenv"
 > bin/pip install python-dotenv     # also installs toplevel module "dotenv" 
 > bin/python
 >>> import dotenv   # which are you using?

   ```
Any ideas how to detect this not at runtime?

There is a lot of code that tries to import a module, and if successful, assumes a specific package is installed.
Eg Flask tries to import dotenv (https://github.com/pallets/flask/blob/main/src/flask/cli.py#L655), 
and then assumes python-dotenv is installed, which might not be the case.

Esp Django-packages have the unfortunate  convention of  "pip install django-foo" and then " import foo", while a foo-package already exists.

**Comment by brettcannon** [comment]
> In that case you still specify something in the packages-attribute in setup.py?

That's for setuptools to create the package; it has nothing to do with us or the resulting metadata beyond the hashes of the files that are contained in e.g. the wheel file.



> Any ideas how to detect this not at runtime?

With 100% certainty? No. Otherwise you can guess based on either what's installed or what files are in the wheel and their names along with where they are supposed to end up once installed.
