### ISSUE TITLE
Marker string format breaks with "win32" in sys_platform

### ISSUE THREAD

**Issue by genericmoniker** [pypa/packaging#75]
I noticed this in pip 8.1.2, but I think the issue is in here.

I have an "extras_require" in my setup.py like:
`extras_require={':"win32" in sys_platform': ['pywin32==219','wmi==1.4.9'],}`

When trying to install the package with pip, I get:

    Invalid requirement: 'pywin32==219; win32 in "sys_platform"'

Something seems to be quoting the variable rather than the value. I'd expect:

    'pywin32==219; "win32" in sys_platform'

Digging through the code, I see markers.py, line 140:

    return '{0} {1} "{2}"'.format(*marker)

This would work for a marker using '==', but not one using 'in', where the order of the variable and value are typically switched. I think this is the problem. This works as expected in pip 8.1.1.

**Comment by meejah** [comment]
@genericmoniker can you confirm that the merge from #76 works for your case?

**Comment by genericmoniker** [comment]
I'm not sure how to assemble a pip to test the scenario end-to-end with the #76 fix, but reviewing the code leads me to believe it would do the trick. Assuming fixed.

**Comment by meejah** [comment]
@genericmoniker crossbar 0.13.2 has a requirement that triggers this bug, so this fails:

```
pip install pip==8.1.2
pip install crossbar=0.13.2
```
