### ISSUE TITLE
How to determine if a specifier set is empty? (Possible feature request)

### ISSUE THREAD

**Issue by notatallshaw** [pypa/packaging#760]
This is a feature request / support question I guess.

I am writing a big resolution optimization for Pip that requires understanding if a specifier set is empty, am I correect in assuming the only way to do that at the moment is: `str(SpecifierSet()) == ""`?

And then if so, my feature request would be to support a `__bool__` that is `True` when the SpecifierSet is not empty and is False when the SpecifierSet is empty. This would save on the `sorted` call that `__str__` makes. Would you be willing to take a PR on this?

**Comment by pradyunsg** [comment]
You can do this with `len(s) == 0` and it should be relatively cheap. I'm wary of defining `__bool__` since it's possible that folks depend on that.

https://github.com/pypa/packaging/blob/769823740a8f5e6b0e37fd05f57f091b56b0ceeb/src/packaging/specifiers.py#L861

**Comment by notatallshaw** [comment]
Ah, perfect thanks!
