### ISSUE TITLE
pyupgrade/black/isort/flake8 → ruff

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [pypa/packaging#765]
This is a suggestion to move from the tools listed in [`.pre-commit-config.yaml`](https://github.com/pypa/packaging/blob/main/.pre-commit-config.yaml) to ruff.

The rationale:
- Ruff is gaining momentum, at least in scientific Python packages, enough to appear as a stable tool available in the long term.
- Simplify by using a single tool to lint and format.
- More [ruff rules](https://docs.astral.sh/ruff/rules/) could be added, specifically [flake8-bugbear](https://github.com/PyCQA/flake8-bugbear).

**Comment by brettcannon** [comment]
I'm supportive of switching if @pradyunsg is.

**Comment by DimitriPapadopoulos** [comment]
See what it would look like in  #769.
