### ISSUE TITLE
shifting aways from pip internal api

### ISSUE THREAD

**Issue by stonebig** [pypa/packaging#77]
hello,

I would like to get the equivalent of:
````
import pip
[(i.key,i.version) for i in pip.get_installed_distributions()]
````
with `packaging` package. 

Is it possible ? Can anyone point me to an example ?

**Comment by xavfernandez** [comment]
It would be simpler to directly use `pkg_resources` (provided by `setuptools`):

    import pkg_resources
    [(i.key, i.version) for i in pkg_resources.working_set]

**Comment by stonebig** [comment]
this one is not internal API ?

**Comment by xavfernandez** [comment]
It is public API, documented here: http://pythonhosted.org/setuptools/pkg_resources.html#workingset-objects

**Comment by stonebig** [comment]
ok, will migrate to this, so. thanks
