### ISSUE TITLE
`canonicalize_name` ignores special meaning of dots in Linux

### ISSUE THREAD

**Issue by chrysle** [pypa/packaging#791]
This behaviour is observable in the following snippet:

```
>>> canonicalize_name("./testdir")
'-/testdir'
>>> canonicalize_name("../testdir")
'-/testdir'
```
Should `packaging` have some logic to detect such paths and keep them as-is on Unix platforms?

**Comment by pradyunsg** [comment]
No. If you run that with `validate=True`, you'll nice that arbitrary Unix paths are not valid PEP 508 specifiers.

You might be mixing the standards-backed model with pip's custom handling of arbitrary paths (see https://pip.pypa.io/en/stable/cli/pip_install/#pip-install, which shows in usage that arbitrary paths are supported).

**Comment by chrysle** [comment]
Thanks for the hint!
