### ISSUE TITLE
CMake nightly version number not parsed correctly

### ISSUE THREAD

**Issue by clin1234** [pypa/packaging#797]
While building `poetry` from source with Python 3.13, this exception was raised: `packaging.version.InvalidVersion: Invalid version: '3.29.20240426-g5deef9c'`

I'm using a nightly build of CMake, which is currently at `3.29.20240426-g5deef9c`.

**Comment by zanieb** [comment]
It doesn't look like that version conforms to the [version specifier specification](https://packaging.python.org/en/latest/specifications/version-specifiers/). What do you expect here? This sounds like an upstream issue, not incorrect parsing.

**Comment by clin1234** [comment]
My mistake. Fixed per rapidfuzz/RapidFuzz#381
