### ISSUE TITLE
Provide function to create valid RPM version?

### ISSUE THREAD

**Issue by toabctl** [pypa/packaging#81]
This is more a question than an issue.
Would you accept a PR to add a new function which can create a valid version for RPM packages from a given version? Same could be done for DEB versions.
This is something that would be very useful when packaging python software and dealing with alpha/beta/rc/post releases .

**Comment by torsava** [comment]
Hi, this project covers this functionality already: https://github.com/gordonmessmer/pyreq2rpm

**Comment by brettcannon** [comment]
I personally would rather stay neutral to external tools outside of the PyPA, and so I would rather have something like this maintained either by the groups that manage RPM and DEB or some other project.

**Comment by dstufft** [comment]
Agreed

**Comment by pradyunsg** [comment]
I agree as well.

**Comment by pradyunsg** [comment]
I'm gonna go ahead and close this now, since all the maintainers agree and a functional alternative has also been provided (thanks @torsava!). :)

Thanks for filing this issue and asking @toabctl! ^>^
