### ISSUE TITLE
Difficult to track down package with bad requirement specification

### ISSUE THREAD

**Issue by jasonwbarnett** [pypa/packaging#811]
So the parser throws an error but it fails to communicate what is the offending package it was parsing when it hit the exception.

source: https://github.com/pypa/packaging/blob/cc938f984bbbe43c5734b9656c9837ab3a28191f/src/packaging/_parser.py#L230

example:

```text
InvalidRequirement: .* suffix can only be used with `==` or `!=` operators
    scikit-learn (>=1.0.*) ; extra == 'pipelines'
```

So this is great in that it highlights what the offense is, but I'm stuck wondering, "which of my *many* 3rd party dependencies is using the bad version specification?"

I found this discussion: https://discuss.python.org/t/should-we-permit-with-more-comparision-operators-in-version-specifiers/22782

Ideally the error message would indicate which package requirement it was parsing and the version of said package.

I ran into this when trying to generate a lock file using [pex][1].

Please let me know if I can provide more information.

p.s. I also saw this mentioned here: https://github.com/pdm-project/pdm/discussions/2211

[1]: https://github.com/pex-tool/pex

**Comment by notatallshaw** [comment]
Not a maintiner, but curious here, Isn't this up to the installer to display?

For example using pip to install a known problematic package I see the problematic package directly before the exception and the name of the wheel with the error:

``` $ pip install --dry-run --no-deps apache-airflow[all]==1.10.12
Collecting apache-airflow==1.10.12 (from apache-airflow[all]==1.10.12)
  Downloading apache_airflow-1.10.12-py2.py3-none-any.whl.metadata (67 kB)
 	━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.6/67.6 kB 2.1 MB/s eta 0:00:00
WARNING: Ignoring version 1.10.12 of apache-airflow since it has invalid metadata:
Requested apache-airflow==1.10.12 from https://files.pythonhosted.org/packages/36/07/368cf47f06564d7ffff603ade4c60039ecf3f5b368b75201f4ccb5512d78/apache_airflow-1.10.12-py2.py3-none-any.whl (from apache-airflow[all]==1.10.12) has invalid metadata: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
	azure-datalake-store (>=0.0.45azure-mgmt-datalake-store>=0.5.0) ; extra == 'all'
                     	~~~~~~~~~~^
Please use pip<24.1 if you need to use this version.
```

**Comment by jasonwbarnett** [comment]
@notatallshaw : I just came to that conclusion after digging into the pex source code. From my limited experience (1 hour) this is something that should be displayed by whatever package manager is leveraging the Requirement class from the packaging library.

**Comment by jasonwbarnett** [comment]
Closing in favor of solving inside the pex project, https://github.com/pex-tool/pex/pull/2440
