### ISSUE TITLE
Changelog is maybe out of date?

### ISSUE THREAD

**Issue by hauntsaninja** [pypa/packaging#838]
There's a packaging 24.1 on PyPI, but no changes mentioned in https://github.com/pypa/packaging/blob/main/CHANGELOG.rst#241---2024-06-10 . 

Also is this changelog entry in the right place? https://github.com/pypa/packaging/pull/777/files#diff-2c623f3c6a917be56c59d43279244996836262cb1e12d9d0786c9c49eef6b43cR27

**Comment by brettcannon** [comment]
Looks like https://github.com/pypa/packaging/releases/tag/24.1 has the changes listed.

**Comment by brettcannon** [comment]
https://github.com/pypa/packaging/blob/main/docs/development/release-process.rst doesn't mention switching our release note process, but @pradyunsg may have simply forgot.

**Comment by pradyunsg** [comment]
Aye, that's indeed what happened here.

**Comment by hauntsaninja** [comment]
Thanks both!
