### ISSUE TITLE
Incompatible version of pyparsing not restricted in setup.py

### ISSUE THREAD

**Issue by Lehych** [pypa/packaging#91]
To reproduce do the following
`virtualenv venv &&  venv/bin/pip install pyparsing==2.0.1 && venv/bin/pip install packaging==16.3 && venv/bin/python -c "import packaging.requirements"`
youll get
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "venv/local/lib/python2.7/site-packages/packaging/requirements.py", line 59, in <module>
    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() takes exactly 2 arguments (1 given)
```

In pyparsing it was fixed here: https://sourceforge.net/p/pyparsing/code/256/ (v 2.0.2)

**Comment by jaraco** [comment]
This issue is much more pressing now that setuptools 34 depends on packaging and pyparsing rather than vendoring them. If something else in the environment has installed an older version of pyparsing, import of pkg_resources will trigger this error.

**Comment by TRManderson** [comment]
Yep, this has broken some of our core tooling. It's a pretty serious issue.

**Comment by ihartwig** [comment]
This bug results in the latest available python3-pip (and likely python3-setuptool) for Ubuntu 14.04LTS to be broken during normal package upgrade. I opened a ticket for the package maintainer side, but they are likely depending on a solution here.
https://bugs.launchpad.net/ubuntu/+source/python-pip/+bug/1676675
