### ISSUE TITLE
Setuptools 34 breaks packaging CI builds

### ISSUE THREAD

**Issue by jaraco** [pypa/packaging#95]
It appears from [this job](https://travis-ci.org/pypa/packaging/builds/196614333) and probably others that the introduction of Setuptools 34 is breaking the tox setup for packaging. The traceback implicates pypa/setuptools#951 and pypa/pip#4264 as the cause.

**Comment by xavfernandez** [comment]
Closed by #102

**Comment by tuukkamustonen** [comment]
@xavfernandez This ticket is still open, though :)

**Comment by xavfernandez** [comment]
Indeed, thanks :)
